import { exportVideo } from './index.js';
import { downloadExportReport, formatExportReport } from './report.js';

const $ = id => document.getElementById(id);
const PRESETS = Object.freeze({ '1080p': { width: 1080, height: 1920, fps: 30 }, '720p': { width: 720, height: 1280, fps: 30 }, '480p': { width: 480, height: 854, fps: 30 }, instagram: { width: 1080, height: 1920, fps: 30 }, tiktok: { width: 1080, height: 1920, fps: 30 } });
function getConfig(preset) { return PRESETS[preset] || PRESETS['720p']; }
function buildFilename(ext) { const clean = value => String(value || '').trim().replace(/[\\/:*?"<>|]+/g, '').replace(/\s+/g, ' '); return `${clean(window.state.audio.metadata.title) || 'Untitled'} - ${clean(window.state.audio.metadata.artist) || 'Unknown Artist'} - KEFE Visualiser.${ext}`; }
function updateUI(stage, percent, message) { const status = $('exportStatus'), pct = $('exportPct'), progress = $('exportProgress'); if (status) status.textContent = message || stage; if (pct) pct.textContent = `${Math.round(percent)}%`; if (progress) progress.value = percent; }
function showDiagnostic(report) {
    const overlay = $('exportOverlay'), status = $('exportStatus'), pct = $('exportPct'), progress = $('exportProgress'), button = $('exportDiagnostic'), cancel = $('cancelExport');
    const text = formatExportReport(report);
    overlay?.classList.remove('hidden');
    if (pct) pct.textContent = 'FAILED';
    if (progress) progress.value = 0;
    if (status) { status.textContent = `Export failed — ${report?.failure?.code || 'EXPORT_UNKNOWN'}`; status.title = text; status.style.whiteSpace = 'pre-wrap'; status.style.userSelect = 'text'; status.dataset.diagnostic = text; }
    if (button) { button.hidden = false; button.disabled = false; button.textContent = 'Download Diagnostics'; button.onclick = () => downloadExportReport(report); }
    if (cancel) { cancel.textContent = 'Close'; cancel.onclick = () => overlay?.classList.add('hidden'); }
    window.kefeLastExportDiagnostic = report;
    console.error('[KEFE EXPORT DIAGNOSTIC REPORT]', report);
}
function seekVideo(video, time, signal) { if (!video || !Number.isFinite(video.duration) || video.duration <= 0) return Promise.resolve(); if (signal?.aborted) return Promise.reject(new DOMException('Export cancelled', 'AbortError')); const target = Math.max(0, Math.min(video.duration, time)); if (Math.abs(video.currentTime - target) < 0.001) return Promise.resolve(); return new Promise((resolve, reject) => { const cleanup = () => { video.removeEventListener('seeked', done); video.removeEventListener('error', fail); signal?.removeEventListener('abort', cancel); }; const done = () => { cleanup(); resolve(); }; const fail = () => { cleanup(); reject(new Error('Background video seek failed')); }; const cancel = () => { cleanup(); reject(new DOMException('Export cancelled', 'AbortError')); }; video.addEventListener('seeked', done, { once: true }); video.addEventListener('error', fail, { once: true }); signal?.addEventListener('abort', cancel, { once: true }); try { video.currentTime = target; } catch (error) { cleanup(); reject(error); } }); }
async function runExport() { const state = window.state, previewCanvas = window.canvas, redraw = window.redrawCurrentPreviewFrame; if (!state || !previewCanvas || typeof redraw !== 'function') throw new Error('KEFE export bridge is not available'); const config = getConfig($('exportPreset')?.value); const target = document.createElement('canvas'); target.width = config.width; target.height = config.height; const media = window.kefeMedia || {}; const signal = window.kefeExportAbort?.signal; const renderFrame = async (ctx, width, height, time) => { await seekVideo(media.video, time, signal); state.playback.currentTime = time; redraw(); ctx.drawImage(previewCanvas, 0, 0, width, height); }; return exportVideo({ state, media, config, createCanvas: () => target, renderFrame, buildFilename, signal, onProgress: ({ stage, percent, message }) => updateUI(stage, percent, message), onDiagnostic: showDiagnostic }); }
window.startOfflineExport = async () => { if (window.isExporting) return; window.isExporting = true; window.kefeLastExportDiagnostic = null; $('exportOverlay')?.classList.remove('hidden'); $('exportDiagnostic')?.setAttribute('hidden', ''); const cancel = $('cancelExport'); if (cancel) { cancel.textContent = 'Cancel'; cancel.onclick = () => window.kefeCancelExport?.(); } window.kefeExportAbort = new AbortController(); try { const result = await runExport(); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.filename; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 30000); updateUI('COMPLETE', 100, 'Export complete'); } catch (error) { console.error('[KEFE] Export failed:', error); if (!error?.stage && !window.kefeLastExportDiagnostic) updateUI('EXPORT_ERROR', Number($('exportProgress')?.value || 0), `Export failed: ${error.message || error}`); } finally { window.isExporting = false; window.kefeExportAbort = null; if (!window.kefeLastExportDiagnostic) setTimeout(() => $('exportOverlay')?.classList.add('hidden'), 1200); } };
window.kefeCancelExport = () => window.kefeExportAbort?.abort();
console.info('[KEFE] Modular export loaded');