const $=s=>document.querySelector(s);const audio=$('#audio');let original={lines:[]},doc={lines:[]},effect='stack',duration=15,accent='#fff',offset=0,selected=0,raf=0;const effects=[['stack','Stack','Moving lines'],['karaoke','Karaoke','Timed word fill'],['type','Type','Timed letter reveal'],['poster','Poster','Large phrase'],['words','Words','Timed word reveal'],['classic','Classic','Clean fade']];
$('#effects').innerHTML=effects.map((e,i)=>`<button class="effect-card ${i?'':'active'}" data-effect="${e[0]}"><strong>${e[1]}</strong><span>${e[2]}</span></button>`).join('');
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(ms){ms=Math.max(0,Math.round(ms));let s=Math.floor(ms/1000),m=Math.floor(s/60);return `${m}:${String(s%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`}function clone(v){return JSON.parse(JSON.stringify(v))}function shiftedStart(l){return Math.max(0,l.start_ms+offset)}
$('#lyricsFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;let form=new FormData();form.append('file',f);let r=await fetch('/api/v1/lyrics/parse',{method:'POST',body:form}),data=await r.json();if(!r.ok)return alert(data.error);if(data.format==='txt')data.lines=data.lines.map((l,i)=>({...l,start_ms:i*2600,duration_ms:2600}));original=clone(data);doc=clone(data);offset=0;$('#offset').value=0;$('#offsetLabel').textContent='0 ms';$('#formatBadge').textContent=data.format.replace('_',' ').toUpperCase();renderTimeline();renderAt(0)};
$('#audioFile').onchange=e=>{let f=e.target.files[0];if(!f)return;audio.src=URL.createObjectURL(f);$('#songName').textContent=f.name.replace(/\.[^.]+$/,'');audio.onloadedmetadata=()=>$('#scrubber').max=Math.min(duration,audio.duration||duration)};
$('#backgroundFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let url=URL.createObjectURL(f),bg=$('#background');bg.innerHTML='';if(f.type.startsWith('video/')){let v=document.createElement('video');v.src=url;v.autoplay=v.loop=v.muted=true;bg.append(v);bg.style.backgroundImage='none'}else bg.style.backgroundImage=`url("${url}")`};
$('#effects').onclick=e=>{let b=e.target.closest('[data-effect]');if(!b)return;effect=b.dataset.effect;document.querySelectorAll('.effect-card').forEach(x=>x.classList.toggle('active',x===b));setStoryClass();renderAt(audio.currentTime*1000)};function setStoryClass(){$('#story').className=`story effect-${effect} backdrop-${$('#backdrop').value}`}
document.querySelectorAll('[data-duration]').forEach(b=>b.onclick=()=>{duration=+b.dataset.duration;document.querySelectorAll('[data-duration]').forEach(x=>x.classList.toggle('active',x===b));$('#scrubber').max=Math.min(duration,audio.duration||duration)});
$('#colorBtn').onclick=()=>{let c=['#ffffff','#ffea00','#ff2d8f','#7c5cff','#00e7ff','#5cff8d'];accent=c[(c.indexOf(accent)+1)%c.length];document.documentElement.style.setProperty('--accent',accent);$('#colorBtn').style.background=accent};$('#size').oninput=e=>$('#lyricsLayer').style.fontSize=e.target.value+'px';$('#position').oninput=e=>$('#lyricsLayer').style.top=e.target.value+'%';$('#align').onchange=e=>$('#lyricsLayer').style.textAlign=e.target.value;$('#backdrop').onchange=setStoryClass;
$('#playBtn').onclick=()=>audio.paused?audio.play():audio.pause();audio.onplay=()=>{$('#playBtn').textContent='❚❚';tick()};audio.onpause=()=>{$('#playBtn').textContent='▶';cancelAnimationFrame(raf)};$('#scrubber').oninput=e=>{audio.currentTime=+e.target.value;renderAt(audio.currentTime*1000)};function tick(){let t=audio.currentTime;$('#scrubber').value=t;$('#clock').textContent=fmt(t*1000);renderAt(t*1000);if(!audio.paused)raf=requestAnimationFrame(tick)}
function currentIndex(ms){let i=0;for(let n=0;n<doc.lines.length;n++){if(shiftedStart(doc.lines[n])<=ms)i=n;else break}return i}function lineSpan(i){let l=doc.lines[i],next=doc.lines[i+1];return Math.max(100,l.duration_ms||((next?shiftedStart(next):shiftedStart(l)+2600)-shiftedStart(l))||2600)}
function wordProgress(line,ms){if(!line.words?.length)return null;let adjusted=ms-offset,active=-1,parts=line.words.map((w,i)=>{let end=w.start_ms+(w.duration_ms||500),p=Math.max(0,Math.min(1,(adjusted-w.start_ms)/Math.max(1,end-w.start_ms)));if(p>0)active=i;return {...w,p}});return {parts,active}}
function easeOutCubic(t){t=Math.max(0,Math.min(1,t));return 1-Math.pow(1-t,3)}
function linePhases(line,ms,span){let p=Math.max(0,Math.min(1,(ms-shiftedStart(line))/Math.max(1,span)));return {p,enter:easeOutCubic(Math.min(1,p/.16)),exit:Math.max(0,Math.min(1,(1-p)/.14))}}
function wordVisuals(line,ms,span){let timed=wordProgress(line,ms);if(timed)return timed.parts.map(w=>({...w,enter:easeOutCubic(Math.min(1,w.p*2.5)),opacity:Math.min(1,w.p*3)}));let words=line.text.split(/\s+/),p=Math.max(0,Math.min(1,(ms-shiftedStart(line))/Math.max(1,span)));return words.map((text,n)=>{let local=Math.max(0,Math.min(1,p*words.length-n));return {text,p:local,enter:easeOutCubic(local),opacity:Math.min(1,local*2.5)}})}
function renderAt(ms){let layer=$('#lyricsLayer');if(!doc.lines.length)return;let i=currentIndex(ms),line=doc.lines[i],span=lineSpan(i),ph=linePhases(line,ms,span),p=ph.p,wp=wordProgress(line,ms);selected=i;layer.style.setProperty('--phase-in',ph.enter);layer.style.setProperty('--phase-out',ph.exit);document.querySelectorAll('.timeline .line').forEach((x,n)=>x.classList.toggle('active',n===i));if(effect==='stack'){layer.innerHTML=[i-1,i,i+1].filter(n=>doc.lines[n]).map(n=>`<div class="lyric-line ${n===i?'current':n>i?'next':''}">${esc(doc.lines[n].text)}</div>`).join('')}else if(effect==='karaoke'){if(wp){layer.innerHTML=`<div class="current-line word-karaoke">${wp.parts.map(w=>`<span class="timed-word" style="--word-progress:${w.p*100}%">${esc(w.text)}</span>`).join(' ')}</div>`}else layer.innerHTML=`<div class="current-line" style="--progress:${p*100}%">${esc(line.text)}</div>`}else if(effect==='type'){let chars;if(wp){chars=wp.parts.reduce((out,w)=>w.p<=0?out:out+(out?' ':'')+w.text.slice(0,Math.max(1,Math.ceil(w.text.length*w.p))),'')}else chars=line.text.slice(0,Math.ceil(line.text.length*p));layer.innerHTML=`<div class="current-line">${esc(chars)}</div>`}else if(effect==='poster'){layer.innerHTML=`<div class="current-line">${esc(line.text)}</div>`}else if(effect==='words'){let words=wordVisuals(line,ms,span);layer.innerHTML=`<div class="current-line">${words.filter(w=>w.p>0).map(w=>`<span class="word" style="--word-enter:${w.enter};--word-opacity:${w.opacity}">${esc(w.text)}</span>`).join(' ')}</div>`}else layer.innerHTML=`<div class="current-line">${esc(line.text)}</div>`}
function renderTimeline(){$('#timeline').innerHTML=doc.lines.map((l,i)=>`<button class="line" data-line="${i}"><span class="time">${fmt(shiftedStart(l))}</span><span class="line-copy"><b>${esc(l.text)}</b><small>${l.words?.length?`${l.words.length} timed words · `:''}${fmt(l.duration_ms||lineSpan(i))}</small></span></button>`).join('')}
$('#offset').oninput=e=>{offset=+e.target.value;$('#offsetLabel').textContent=`${offset>0?'+':''}${offset} ms`;renderTimeline();renderAt(audio.currentTime*1000)};document.querySelector('.nudge').onclick=e=>{let b=e.target.closest('[data-nudge]');if(!b||!doc.lines[selected])return;doc.lines[selected].start_ms=Math.max(0,doc.lines[selected].start_ms+(+b.dataset.nudge));renderTimeline();renderAt(audio.currentTime*1000)};$('#tapSync').onclick=()=>{if(!doc.lines.length)return;let l=doc.lines[selected];l.start_ms=Math.max(0,Math.round(audio.currentTime*1000)-offset);if(selected>0&&l.start_ms<doc.lines[selected-1].start_ms)l.start_ms=doc.lines[selected-1].start_ms+10;renderTimeline();renderAt(audio.currentTime*1000)};$('#resetTiming').onclick=()=>{doc=clone(original);offset=0;$('#offset').value=0;$('#offsetLabel').textContent='0 ms';renderTimeline();renderAt(audio.currentTime*1000)};
$('#timeline').onclick=e=>{let b=e.target.closest('[data-line]');if(!b)return;selected=+b.dataset.line;let l=doc.lines[selected];$('#editText').value=l.text;$('#editStart').value=l.start_ms;$('#editDuration').value=l.duration_ms||lineSpan(selected);$('#wordTimingSummary').textContent=l.words?.length?`${l.words.length} enhanced-LRC word timestamps are attached to this line.`:'No word-level timestamps. Karaoke uses line progress.';$('#lineDialog').showModal()};$('#saveLine').onclick=e=>{e.preventDefault();let l=doc.lines[selected];l.text=$('#editText').value.trim()||l.text;l.start_ms=Math.max(0,+$('#editStart').value||0);l.duration_ms=Math.max(100,+$('#editDuration').value||2600);doc.lines.sort((a,b)=>a.start_ms-b.start_ms);$('#lineDialog').close();renderTimeline();renderAt(audio.currentTime*1000)};
$('#exportBtn').onclick=()=>alert('Precision timing is ready. MP4 rendering arrives in the export milestone.');fetch('/api/v1/templates').catch(()=>{});

// Milestone 4: direct manipulation and background composition.
const story=$('#story'),lyricsLayer=$('#lyricsLayer'),background=$('#background'),gradientLayer=$('#gradientLayer'),safeGuides=$('#safeGuides');
let transformState={x:0,y:0,scale:1,rotation:0};
let pointers=new Map(),gestureStart=null,backgroundVideo=null,backgroundURL=null;
function applyTransform(){lyricsLayer.style.setProperty('--drag-x',`${transformState.x}px`);lyricsLayer.style.setProperty('--drag-y',`${transformState.y}px`);lyricsLayer.style.setProperty('--lyric-scale',transformState.scale);lyricsLayer.style.setProperty('--lyric-rotation',`${transformState.rotation}deg`)}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function resetTransform(){transformState={x:0,y:0,scale:1,rotation:0};applyTransform()}
function pointDistance(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function pointAngle(a,b){return Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI}
function pointerPair(){return [...pointers.values()].slice(0,2)}
lyricsLayer.addEventListener('pointerdown',e=>{lyricsLayer.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)gestureStart={kind:'drag',x:e.clientX,y:e.clientY,baseX:transformState.x,baseY:transformState.y};else if(pointers.size===2){let [a,b]=pointerPair();gestureStart={kind:'pinch',distance:pointDistance(a,b),angle:pointAngle(a,b),scale:transformState.scale,rotation:transformState.rotation}}});
lyricsLayer.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&gestureStart?.kind==='drag'){transformState.x=gestureStart.baseX+e.clientX-gestureStart.x;transformState.y=gestureStart.baseY+e.clientY-gestureStart.y}else if(pointers.size>=2){let [a,b]=pointerPair();if(gestureStart?.kind!=='pinch')gestureStart={kind:'pinch',distance:pointDistance(a,b),angle:pointAngle(a,b),scale:transformState.scale,rotation:transformState.rotation};transformState.scale=clamp(gestureStart.scale*(pointDistance(a,b)/Math.max(1,gestureStart.distance)),.45,2.5);transformState.rotation=clamp(gestureStart.rotation+pointAngle(a,b)-gestureStart.angle,-180,180)}applyTransform()});
function releasePointer(e){pointers.delete(e.pointerId);if(pointers.size===1){let a=[...pointers.values()][0];gestureStart={kind:'drag',x:a.x,y:a.y,baseX:transformState.x,baseY:transformState.y}}else if(!pointers.size)gestureStart=null}
lyricsLayer.addEventListener('pointerup',releasePointer);lyricsLayer.addEventListener('pointercancel',releasePointer);
lyricsLayer.addEventListener('wheel',e=>{e.preventDefault();if(e.shiftKey)transformState.rotation=clamp(transformState.rotation+Math.sign(e.deltaY)*2,-180,180);else transformState.scale=clamp(transformState.scale-Math.sign(e.deltaY)*.05,.45,2.5);applyTransform()},{passive:false});
$('#resetTransform').onclick=resetTransform;$('#centreText').onclick=()=>{transformState.x=0;transformState.y=0;applyTransform()};
$('#toggleGuides').onclick=e=>{safeGuides.classList.toggle('hidden');e.currentTarget.classList.toggle('active',!safeGuides.classList.contains('hidden'))};
$('#blur').oninput=e=>background.style.setProperty('--background-blur',`${e.target.value}px`);
$('#dim').oninput=e=>story.style.setProperty('--story-dim',`${e.target.value/100}`);
const gradients={none:'transparent',sunset:'linear-gradient(160deg,#ff5f6d88,#ffc37122 45%,#6a11cb88)',ocean:'linear-gradient(160deg,#00c6ff88,#0072ff44 45%,#07195299)',violet:'linear-gradient(160deg,#fc466b66,#3f5efb88)',mono:'linear-gradient(180deg,#0002,#000b)'};
$('#gradient').onchange=e=>gradientLayer.style.background=gradients[e.target.value]||'transparent';
$('#fitCover').onclick=()=>{background.classList.remove('fit-contain');background.classList.add('fit-cover')};
$('#fitContain').onclick=()=>{background.classList.remove('fit-cover');background.classList.add('fit-contain')};
$('#videoStart').oninput=e=>{if(backgroundVideo){backgroundVideo.currentTime=+e.target.value;backgroundVideo.play().catch(()=>{})}};
const originalBackgroundHandler=$('#backgroundFile').onchange;
$('#backgroundFile').onchange=e=>{let f=e.target.files[0];if(!f)return;if(backgroundURL)URL.revokeObjectURL(backgroundURL);backgroundURL=URL.createObjectURL(f);background.innerHTML='';background.style.backgroundImage='none';backgroundVideo=null;$('#videoStart').max=0;$('#videoStart').value=0;if(f.type.startsWith('video/')){let v=document.createElement('video');backgroundVideo=v;v.src=backgroundURL;v.autoplay=true;v.loop=true;v.muted=true;v.playsInline=true;v.onloadedmetadata=()=>{$('#videoStart').max=Math.max(0,v.duration-.1);v.currentTime=0};background.append(v);v.play().catch(()=>{})}else{background.style.backgroundImage=`url("${backgroundURL}")`}};
applyTransform();

const fontStyle=$('#fontStyle');function applyFontStyle(){story.classList.remove('font-rounded','font-classic','font-condensed','font-serif');story.classList.add('font-'+(fontStyle?.value||'rounded'));renderAt(audio.currentTime*1000)}if(fontStyle){fontStyle.onchange=applyFontStyle;applyFontStyle()}
