// LINA — typography control hardening and font-state preservation.
(function(){
'use strict';
const $=s=>document.querySelector(s),KEY='lyricVideoVisualier.typeControls.v2',defaults={size:54,lineSpacing:.98,letterSpacing:-.035};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}let state=load();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function clamp(n,min,max){n=Number(n);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):min}
function ensureValueLabel(input,suffix=''){let out=input.parentElement?.querySelector(`[data-value-for="${input.id}"]`);if(!out){out=document.createElement('span');out.dataset.valueFor=input.id;out.className='range-value';input.insertAdjacentElement('beforebegin',out)}out.textContent=`${input.value}${suffix}`}
function applyPreview(){const layer=$('#lyricsLayer');if(!layer)return;state.size=clamp(state.size,6,200);state.lineSpacing=clamp(state.lineSpacing,.55,2.5);state.letterSpacing=clamp(state.letterSpacing,-.12,.5);layer.style.fontSize=`${state.size}px`;layer.style.lineHeight=String(state.lineSpacing);layer.style.letterSpacing=`${state.letterSpacing}em`;layer.style.setProperty('--lv-line-spacing',state.lineSpacing);layer.style.setProperty('--lv-letter-spacing',`${state.letterSpacing}em`)}
function configureSize(){const input=$('#size');if(!input)return;input.min='6';input.max='200';input.step='1';input.value=String(clamp(state.size,6,200));ensureValueLabel(input,' px');const sync=()=>{state.size=+input.value;ensureValueLabel(input,' px');applyPreview();save()};input.addEventListener('input',sync,{capture:true});input.addEventListener('change',sync,{capture:true})}
function addSpacingControls(){const size=$('#size'),grid=size?.closest('.grid');if(!grid)return;let line=$('#lineSpacing');if(!line){const label=document.createElement('label');label.innerHTML='Line spacing <span data-value-for="lineSpacing"></span><input id="lineSpacing" type="range" min="0.55" max="2.50" step="0.01">';size.closest('label')?.insertAdjacentElement('afterend',label);line=label.querySelector('input')}let letter=$('#letterSpacing');if(!letter){const label=document.createElement('label');label.innerHTML='Letter spacing <span data-value-for="letterSpacing"></span><input id="letterSpacing" type="range" min="-0.12" max="0.50" step="0.005">';line.closest('label')?.insertAdjacentElement('afterend',label);letter=label.querySelector('input')}line.value=String(clamp(state.lineSpacing,.55,2.5));letter.value=String(clamp(state.letterSpacing,-.12,.5));ensureValueLabel(line,'×');ensureValueLabel(letter,' em');line.addEventListener('input',()=>{state.lineSpacing=+line.value;ensureValueLabel(line,'×');applyPreview();save()},{capture:true});letter.addEventListener('input',()=>{state.letterSpacing=+letter.value;ensureValueLabel(letter,' em');applyPreview();save()},{capture:true})}
function preserveFontClass(){const story=$('#story'),select=$('#fontStyle');if(!story||!select)return;const wanted=`font-${select.value||'helvetica'}`;[...story.classList].filter(c=>c.startsWith('font-')&&c!==wanted).forEach(c=>story.classList.remove(c));story.classList.add(wanted)}
function installFontGuard(){const story=$('#story'),select=$('#fontStyle');if(!story||!select)return;select.addEventListener('change',preserveFontClass,{capture:false});const mo=new MutationObserver(()=>preserveFontClass());mo.observe(story,{attributes:true,attributeFilter:['class']});preserveFontClass()}
function installMutationGuard(){const layer=$('#lyricsLayer');if(!layer)return;new MutationObserver(()=>requestAnimationFrame(applyPreview)).observe(layer,{childList:true,subtree:true})}
function installCSS(){if($('#lv-control-fixes-style'))return;const s=document.createElement('style');s.id='lv-control-fixes-style';s.textContent=`.grid label{position:relative}.range-value{display:block;justify-self:end;margin-top:-18px;font:700 10px/1 "Helvetica Neue",Helvetica,Arial,sans-serif;color:#f3f3f3;font-variant-numeric:tabular-nums;pointer-events:none}.grid input[type=range]{min-width:0;touch-action:pan-y}.lyrics-layer{line-height:var(--lv-line-spacing,.98)!important;letter-spacing:var(--lv-letter-spacing,-.035em)!important}`;document.head.appendChild(s)}
function patchExportTypography(){if(typeof window.drawTextLine!=='function')return;const base=window.drawTextLine;window.drawTextLine=function(ctx,text,x,y,maxWidth,fontPx,align='center',alpha=1,weight=800){if('letterSpacing'in ctx)try{ctx.letterSpacing=`${state.letterSpacing*fontPx}px`}catch{}return base(ctx,text,x,y,maxWidth,fontPx,align,alpha,weight)}}
function repairRanges(){document.querySelectorAll('input[type="range"]').forEach(r=>{if(r.min!==''&&r.max!==''&&+r.min>+r.max){const a=r.min;r.min=r.max;r.max=a}if(r.step!==''&&(!Number.isFinite(+r.step)||+r.step<=0))r.step='any'})}
function init(){installCSS();configureSize();addSpacingControls();repairRanges();applyPreview();installMutationGuard();installFontGuard();patchExportTypography();setTimeout(()=>{repairRanges();applyPreview();preserveFontClass();patchExportTypography()},400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
