// Milestone 7: browser canvas renderer + Mac FFmpeg MP4 conversion.
const exportDialog=$('#exportDialog'),exportCanvas=$('#exportCanvas'),exportCtx=exportCanvas.getContext('2d',{alpha:false});
let exportAbort=false,activeRecorder=null,exportWakeLock=null;
const EXPORT_RECOVERY_KEY='story-lyrics-export-recovery-v1';
let recoveryBlob=null,recoveryName='Story-Lyrics';
function exportStatus(message,progress){$('#exportStatus').textContent=message;if(Number.isFinite(progress))$('#exportProgress').value=progress}
async function requestExportWakeLock(){try{if('wakeLock' in navigator)exportWakeLock=await navigator.wakeLock.request('screen')}catch{}}
async function releaseExportWakeLock(){try{await exportWakeLock?.release()}catch{}exportWakeLock=null}
function saveExportRecovery(blob,name){recoveryBlob=blob;recoveryName=name||'Story-Lyrics';try{sessionStorage.setItem(EXPORT_RECOVERY_KEY,JSON.stringify({name:recoveryName,size:blob.size,type:blob.type,createdAt:Date.now()}))}catch{}showRecoveryActions()}
function clearExportRecovery(){recoveryBlob=null;try{sessionStorage.removeItem(EXPORT_RECOVERY_KEY)}catch{}showRecoveryActions()}
function showRecoveryActions(){const box=$('#recoveryActions');if(box)box.classList.toggle('hidden',!recoveryBlob)}
function supportedRecordingMime(){const candidates=['video/mp4;codecs=h264,aac','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];return candidates.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||''}
async function projectMediaBlob(kind){if(kind==='audio'&&selectedAudioFile)return selectedAudioFile;if(kind==='background'&&selectedBackgroundFile)return selectedBackgroundFile;const item=await getMedia(activeProjectID(),kind);return item?.blob?new File([item.blob],item.name||kind,{type:item.type||item.blob.type}):null}
function hexToRGBA(hex,a=1){let h=hex.replace('#','');if(h.length===3)h=h.split('').map(x=>x+x).join('');const n=parseInt(h,16);return `rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}
function roundedRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function wrapWords(ctx,text,maxWidth){const words=String(text||'').split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines}
function exportLineIndex(ms){let i=0;for(let n=0;n<doc.lines.length;n++){if(shiftedStart(doc.lines[n])<=ms)i=n;else break}return i}
function exportLineSpan(i){const l=doc.lines[i],next=doc.lines[i+1];return Math.max(100,l.duration_ms||((next?shiftedStart(next):shiftedStart(l)+2600)-shiftedStart(l))||2600)}
function drawFittedMedia(ctx,media,w,h,mode='cover'){const sw=media.videoWidth||media.naturalWidth||w,sh=media.videoHeight||media.naturalHeight||h;if(!sw||!sh)return;const scale=mode==='contain'?Math.min(w/sw,h/sh):Math.max(w/sw,h/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(media,(w-dw)/2,(h-dh)/2,dw,dh)}
async function prepareBackground(file){if(!file)return null;const url=URL.createObjectURL(file);if(file.type.startsWith('video/')){const v=document.createElement('video');v.src=url;v.muted=true;v.playsInline=true;v.preload='auto';await new Promise((res,rej)=>{v.onloadeddata=res;v.onerror=rej});return {kind:'video',media:v,url}}const img=new Image();img.src=url;await img.decode();return {kind:'image',media:img,url}}
function drawGradient(ctx,w,h,name){let g;if(name==='sunset'){g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(255,95,109,.55)');g.addColorStop(.45,'rgba(255,195,113,.12)');g.addColorStop(1,'rgba(106,17,203,.55)')}else if(name==='ocean'){g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(0,198,255,.55)');g.addColorStop(.5,'rgba(0,114,255,.28)');g.addColorStop(1,'rgba(7,25,82,.65)')}else if(name==='violet'){g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(252,70,107,.4)');g.addColorStop(1,'rgba(63,94,251,.55)')}else if(name==='mono'){g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,.1)');g.addColorStop(1,'rgba(0,0,0,.7)')}if(g){ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}}
function exportFontFamily(){const v=$('#fontStyle')?.value||'rounded';if(v==='serif')return 'Georgia,Times New Roman,serif';if(v==='condensed')return 'Arial Narrow,Helvetica Neue Condensed,Arial,sans-serif';if(v==='classic')return '-apple-system,BlinkMacSystemFont,Helvetica Neue,Arial,sans-serif';return '-apple-system,BlinkMacSystemFont,Arial Rounded MT Bold,Arial,sans-serif'}
function exportEase(t){t=Math.max(0,Math.min(1,t));return 1-Math.pow(1-t,3)}
function drawTextLine(ctx,text,x,y,maxWidth,fontPx,align='center',alpha=1,weight=800){ctx.save();ctx.globalAlpha=alpha;ctx.font=`${weight} ${fontPx}px ${exportFontFamily()}`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.lineJoin='round';ctx.strokeStyle='rgba(0,0,0,.28)';ctx.lineWidth=Math.max(3,fontPx*.08);const lines=wrapWords(ctx,text,maxWidth),lh=fontPx*1.08,total=(lines.length-1)*lh;lines.forEach((line,i)=>{ctx.strokeText(line,x,y-total/2+i*lh);ctx.fillText(line,x,y-total/2+i*lh)});ctx.restore()}
function drawExportLyrics(ctx,ms,w,h){if(!doc.lines.length)return;const i=exportLineIndex(ms),line=doc.lines[i],span=exportLineSpan(i),p=Math.max(0,Math.min(1,(ms-shiftedStart(line))/span)),enter=exportEase(Math.min(1,p/.16)),exit=Math.max(0,Math.min(1,(1-p)/.14));const baseFont=+$('#size').value*(w/390),maxWidth=w*.82;let x=w/2;if($('#align').value==='left')x=w*.1;if($('#align').value==='right')x=w*.9;let y=h*(+$('#position').value/100)+transformState.y*(w/390);ctx.save();ctx.translate(x+transformState.x*(w/390),y);ctx.rotate(transformState.rotation*Math.PI/180);ctx.scale(transformState.scale,transformState.scale);ctx.translate(-x,-y);ctx.fillStyle=accent;
 const backdrop=$('#backdrop').value;if(backdrop!=='none'){ctx.save();ctx.fillStyle=backdrop==='solid'?'rgba(0,0,0,.72)':'rgba(0,0,0,.35)';roundedRect(ctx,w*.06,y-baseFont*1.4,w*.88,baseFont*2.8,baseFont*.35);ctx.fill();ctx.restore()}
 if(effect==='stack'){[-1,0,1].forEach((d)=>{const l=doc.lines[i+d];if(!l)return;ctx.fillStyle=d===0?accent:'rgba(255,255,255,.48)';const scale=d===0?.96+enter*.06:1;ctx.save();ctx.translate(x,y+d*baseFont*1.55);ctx.scale(scale,scale);ctx.translate(-x,-(y+d*baseFont*1.55));drawTextLine(ctx,l.text,x,y+d*baseFont*1.55,maxWidth,d===0?baseFont:baseFont*.72,$('#align').value,d===0?exit:.72,d===0?850:650);ctx.restore()})}
 else if(effect==='karaoke'){ctx.fillStyle='rgba(255,255,255,.38)';drawTextLine(ctx,line.text,x,y,maxWidth,baseFont,$('#align').value,exit,850);if(line.words?.length){let adjusted=ms-offset;let cursor=0;ctx.save();for(const word of line.words){const end=word.start_ms+(word.duration_ms||500),wp=Math.max(0,Math.min(1,(adjusted-word.start_ms)/Math.max(1,end-word.start_ms)));const prefix=line.text.slice(0,cursor),wordStart=ctx.measureText(prefix).width,wordWidth=ctx.measureText(word.text).width;ctx.beginPath();ctx.rect(Math.max(0,x-maxWidth/2+wordStart),0,wordWidth*wp+4,h);ctx.clip();cursor+=word.text.length+1}ctx.fillStyle=accent;drawTextLine(ctx,line.text,x,y,maxWidth,baseFont,$('#align').value,exit,850);ctx.restore()}else{ctx.save();ctx.beginPath();ctx.rect(0,0,w*p,h);ctx.clip();ctx.fillStyle=accent;drawTextLine(ctx,line.text,x,y,maxWidth,baseFont,$('#align').value,exit,850);ctx.restore()}}
 else if(effect==='type'){let shown;if(line.words?.length){let adjusted=ms-offset;shown=line.words.reduce((out,word)=>{const end=word.start_ms+(word.duration_ms||500),wp=Math.max(0,Math.min(1,(adjusted-word.start_ms)/Math.max(1,end-word.start_ms)));if(wp<=0)return out;return out+(out?' ':'')+word.text.slice(0,Math.max(1,Math.ceil(word.text.length*wp)))},'')}else shown=line.text.slice(0,Math.ceil(line.text.length*p));ctx.fillStyle=accent;drawTextLine(ctx,shown,x,y,maxWidth,baseFont,$('#align').value,exit,800)}
 else if(effect==='poster'){const scale=.82+enter*.18;ctx.translate(x,y);ctx.scale(scale,scale);ctx.translate(-x,-y);ctx.fillStyle=accent;drawTextLine(ctx,line.text,x,y,w*.9,baseFont*1.35,$('#align').value,exit,900)}
 else if(effect==='words'){const words=line.text.split(/\s+/);let shown=[];for(let n=0;n<words.length;n++){let wp;if(line.words?.[n]){const wr=line.words[n],end=wr.start_ms+(wr.duration_ms||500);wp=Math.max(0,Math.min(1,(ms-offset-wr.start_ms)/Math.max(1,end-wr.start_ms)))}else wp=Math.max(0,Math.min(1,p*words.length-n));if(wp>0)shown.push(words[n])}ctx.fillStyle=accent;drawTextLine(ctx,shown.join(' '),x,y,maxWidth,baseFont,$('#align').value,exit,850)}
 else {ctx.fillStyle=accent;drawTextLine(ctx,line.text,x,y+(1-enter)*12,maxWidth,baseFont,$('#align').value,Math.max(.05,exit),750)}ctx.restore()}
function drawMusicTag(ctx,w,h){ctx.save();ctx.fillStyle='rgba(0,0,0,.42)';roundedRect(ctx,w*.055,h*.89,w*.62,h*.055,h*.0275);ctx.fill();ctx.fillStyle='#fff';ctx.font=`700 ${w*.032}px -apple-system,Arial`;ctx.textBaseline='middle';ctx.fillText('♫  '+($('#songName').textContent||'Original audio'),w*.085,h*.917);ctx.restore()}
async function renderStoryFrame(ctx,bg,elapsedMs,w,h){ctx.save();ctx.fillStyle='#111';ctx.fillRect(0,0,w,h);if(bg){if(bg.kind==='video'&&bg.media.readyState>=2)drawFittedMedia(ctx,bg.media,w,h,background.classList.contains('fit-contain')?'contain':'cover');if(bg.kind==='image')drawFittedMedia(ctx,bg.media,w,h,background.classList.contains('fit-contain')?'contain':'cover')}const dim=+$('#dim').value/100;if(dim){ctx.fillStyle=`rgba(0,0,0,${dim})`;ctx.fillRect(0,0,w,h)}drawGradient(ctx,w,h,$('#gradient').value);drawExportLyrics(ctx,elapsedMs,w,h);drawMusicTag(ctx,w,h);ctx.restore()}
async function recordCanvasStory({quality,startSeconds,seconds,audioFile,backgroundFile}){if(!exportCanvas.captureStream||!window.MediaRecorder)throw new Error('This browser cannot record the Story canvas. Update Safari or use Chrome on the Mac.');const lowMemory=$('#lowMemoryExport')?.checked||false;const target=lowMemory?Math.min(720,quality):quality;const fps=lowMemory?24:30;const w=target,h=Math.round(target*16/9);exportCanvas.width=w;exportCanvas.height=h;const bg=await prepareBackground(backgroundFile);const stream=exportCanvas.captureStream(fps);const ac=new (window.AudioContext||window.webkitAudioContext)();const dest=ac.createMediaStreamDestination();const audioBytes=await audioFile.arrayBuffer();const audioBuffer=await ac.decodeAudioData(audioBytes.slice(0));const source=ac.createBufferSource();source.buffer=audioBuffer;source.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const mime=supportedRecordingMime(),chunks=[];const bitrate=lowMemory?3500000:(target>=1080?10000000:5500000);const rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:bitrate}:undefined);activeRecorder=rec;rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const completed=new Promise((resolve,reject)=>{rec.onstop=()=>resolve(new Blob(chunks,{type:rec.mimeType||mime||'video/webm'}));rec.onerror=()=>reject(rec.error||new Error('Recording failed'))});rec.start(lowMemory?500:1000);const offsetSeconds=Math.min(startSeconds,audioBuffer.duration-.01);source.start(ac.currentTime+.08,Math.max(0,offsetSeconds),Math.min(seconds,audioBuffer.duration-offsetSeconds));if(bg?.kind==='video'){bg.media.currentTime=Math.min(+$('#videoStart').value||0,Math.max(0,bg.media.duration-.1));await bg.media.play().catch(()=>{})}const began=performance.now();await new Promise((resolve,reject)=>{function frame(now){if(exportAbort){reject(new Error('Export cancelled'));return}const elapsed=(now-began)/1000;if(bg?.kind==='video'&&Number.isFinite(bg.media.duration)&&bg.media.duration>0){const base=+$('#videoStart').value||0,desired=(base+elapsed)%bg.media.duration;if(Math.abs(bg.media.currentTime-desired)>.18)bg.media.currentTime=desired}renderStoryFrame(exportCtx,bg,(startSeconds+elapsed)*1000,w,h);exportStatus(`Rendering ${elapsed.toFixed(1)} of ${seconds}s…`,Math.min(88,elapsed/seconds*88));if(elapsed<seconds)requestAnimationFrame(frame);else resolve()}requestAnimationFrame(frame)}).finally(()=>{if(bg?.kind==='video')bg.media.pause()});rec.stop();try{source.stop()}catch{}const blob=await completed;stream.getTracks().forEach(t=>t.stop());await ac.close();if(bg)URL.revokeObjectURL(bg.url);activeRecorder=null;return blob}
async function transcodeToMP4(blob,name){exportStatus('Converting to MP4 on your Mac…',92);const ext=blob.type.includes('mp4')?'mp4':'webm',form=new FormData();form.append('video',blob,`story-recording.${ext}`);form.append('name',name);let response;for(let attempt=1;attempt<=3;attempt++){try{response=await fetch('/api/v1/export/transcode',{method:'POST',body:form});if(response.ok||response.status<500)break}catch(err){if(attempt===3)throw err}await new Promise(r=>setTimeout(r,attempt*900))}if(!response.ok){let message='MP4 conversion failed';try{message=(await response.json()).error||message}catch{}throw new Error(message)}return {blob:await response.blob(),filename:(response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)||[])[1]||'Story-Lyrics.mp4'} }
async function downloadOrShare(fileBlob,filename){const file=new File([fileBlob],filename,{type:'video/mp4'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'Story Lyrics export'});return}catch(err){if(err?.name!=='AbortError')console.warn('Share failed; falling back to download',err)}}const url=URL.createObjectURL(fileBlob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
$('#retryConversion').onclick=async()=>{if(!recoveryBlob)return;try{await requestExportWakeLock();const mp4=await transcodeToMP4(recoveryBlob,recoveryName);exportStatus('Recovered MP4 ready',100);await downloadOrShare(mp4.blob,mp4.filename);if(typeof recordExportHistory==='function')recordExportHistory(mp4.filename,mp4.blob.size);clearExportRecovery();notify('Recovered Story MP4 exported')}catch(err){exportStatus(err.message||'Recovery failed',0)}finally{await releaseExportWakeLock()}};
$('#discardRecovery').onclick=clearExportRecovery;
$('#exportBtn').onclick=()=>{const max=Math.max(0,(audio.duration||duration)-duration);$('#exportStart').max=max.toFixed(1);$('#exportStart').value=Math.min(audio.currentTime||0,max).toFixed(1);exportStatus('Ready',0);exportDialog.showModal()};
$('#cancelExport').onclick=()=>{exportAbort=true;if(activeRecorder?.state==='recording')activeRecorder.stop()};
$('#beginExport').onclick=async()=>{exportAbort=false;await requestExportWakeLock();const button=$('#beginExport');button.disabled=true;try{const audioFile=await projectMediaBlob('audio');if(!audioFile)throw new Error('Add an audio file before exporting.');if(!doc.lines.length)throw new Error('Add lyrics before exporting.');const backgroundFile=await projectMediaBlob('background');const quality=+$('#exportQuality').value,startSeconds=Math.max(0,+$('#exportStart').value||0),seconds=Math.min(duration,Math.max(.1,(audio.duration||duration)-startSeconds));exportStatus('Preparing audio and canvas…',2);saveCurrentProject(true);const recorded=await recordCanvasStory({quality,startSeconds,seconds,audioFile,backgroundFile});if(exportAbort)throw new Error('Export cancelled');const projectName=$('#projectName').value.trim()||'Story-Lyrics';saveExportRecovery(recorded,projectName);const mp4=await transcodeToMP4(recorded,projectName);exportStatus('MP4 ready',100);await downloadOrShare(mp4.blob,mp4.filename);if(typeof recordExportHistory==='function')recordExportHistory(mp4.filename,mp4.blob.size);clearExportRecovery();notify('Story MP4 exported');setTimeout(()=>exportDialog.close(),500)}catch(err){exportStatus(err.message||'Export failed',0)}finally{button.disabled=false;await releaseExportWakeLock()}};
window.addEventListener('pagehide',()=>{if(activeRecorder?.state==='recording')activeRecorder.requestData()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&activeRecorder?.state==='recording')requestExportWakeLock()});
showRecoveryActions();
