// LINA — local canvas video exporter with audio, lyric effects, casing and typography parity.
'use strict';
const exportDialog=$('#exportDialog'),exportCanvas=$('#exportCanvas'),exportCtx=exportCanvas.getContext('2d',{alpha:false});
let exportAbort=false,activeRecorder=null,exportWakeLock=null;
function exportStatus(message,progress){$('#exportStatus').textContent=message;if(Number.isFinite(progress))$('#exportProgress').value=progress}
async function requestExportWakeLock(){try{if('wakeLock'in navigator)exportWakeLock=await navigator.wakeLock.request('screen')}catch{}}
async function releaseExportWakeLock(){try{await exportWakeLock?.release()}catch{}exportWakeLock=null}
function supportedRecordingMime(){const c=['video/mp4;codecs=h264,aac','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];return c.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||''}
async function projectMediaBlob(kind){const direct=kind==='audio'?window.selectedAudioFile:window.selectedBackgroundFile;if(direct)return direct;try{const item=await getMedia(activeProjectID(),kind);return item?.blob?new File([item.blob],item.name||kind,{type:item.type||item.blob.type}):null}catch{return null}}
function roundedRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));ctx.closePath()}
function wrapWords(ctx,text,maxWidth){const words=String(text||'').trim().split(/\s+/),rows=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width<=maxWidth){line=test;continue}if(line)rows.push(line);line=word}if(line)rows.push(line);return rows.length?rows:['']}
function exportFontFamily(){const v=$('#fontStyle')?.value||'helvetica';if(v==='serif')return 'Georgia,"Times New Roman",serif';if(v==='condensed')return '"Arial Narrow","Helvetica Neue Condensed",Arial,sans-serif';if(v==='rounded')return '-apple-system,BlinkMacSystemFont,"Arial Rounded MT Bold",Arial,sans-serif';return '"Helvetica Neue",Helvetica,Arial,sans-serif'}
function exportText(v=''){return typeof displayText==='function'?displayText(v):String(v)}
function drawTextLine(ctx,text,x,y,maxWidth,fontPx,align='center',alpha=1,weight=800){ctx.save();ctx.globalAlpha=alpha;ctx.font=`${weight} ${fontPx}px ${exportFontFamily()}`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.lineJoin='round';ctx.strokeStyle='rgba(0,0,0,.28)';ctx.lineWidth=Math.max(2,fontPx*.055);const rows=wrapWords(ctx,exportText(text),maxWidth),spacing=Number($('#lineSpacing')?.value||.98),lh=fontPx*spacing,total=(rows.length-1)*lh;rows.forEach((row,i)=>{const yy=y-total/2+i*lh;ctx.strokeText(row,x,yy);ctx.fillText(row,x,yy)});ctx.restore()}
window.drawTextLine=drawTextLine;window.wrapWords=wrapWords;window.exportFontFamily=exportFontFamily;
function exportLineIndex(ms){let i=0;for(let n=0;n<doc.lines.length;n++){if(shiftedStart(doc.lines[n])<=ms)i=n;else break}return i}
function exportLineSpan(i){const l=doc.lines[i],next=doc.lines[i+1];return Math.max(100,l.duration_ms||((next?shiftedStart(next):shiftedStart(l)+2600)-shiftedStart(l))||2600)}
function drawFittedMedia(ctx,media,w,h,mode='cover'){const sw=media.videoWidth||media.naturalWidth||media.width,sh=media.videoHeight||media.naturalHeight||media.height;if(!sw||!sh)return;const s=mode==='contain'?Math.min(w/sw,h/sh):Math.max(w/sw,h/sh),dw=sw*s,dh=sh*s;ctx.drawImage(media,(w-dw)/2,(h-dh)/2,dw,dh)}
async function prepareBackground(file){if(!file)return null;const url=URL.createObjectURL(file);if(file.type.startsWith('video/')){const v=document.createElement('video');v.src=url;v.muted=true;v.playsInline=true;v.preload='auto';await new Promise((r,j)=>{v.onloadeddata=r;v.onerror=j});return {kind:'video',media:v,url}}const img=new Image();img.src=url;await img.decode();return {kind:'image',media:img,url}}
function drawGradient(ctx,w,h,name){let g;if(name==='sunset'){g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(255,95,109,.55)');g.addColorStop(1,'rgba(106,17,203,.55)')}else if(name==='ocean'){g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(0,198,255,.55)');g.addColorStop(1,'rgba(7,25,82,.65)')}else if(name==='violet'){g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(252,70,107,.4)');g.addColorStop(1,'rgba(63,94,251,.55)')}else if(name==='mono'){g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,.1)');g.addColorStop(1,'rgba(0,0,0,.7)')}if(g){ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}}
function drawExportLyrics(ctx,ms,w,h){if(!doc.lines.length)return;const i=exportLineIndex(ms),line=doc.lines[i],span=exportLineSpan(i),p=Math.max(0,Math.min(1,(ms-shiftedStart(line))/span)),base=+$('#size').value*(w/390),max=w*.82,align=$('#align').value;let x=align==='left'?w*.1:align==='right'?w*.9:w/2,y=h*(+$('#position').value/100)+transformState.y*(w/390);ctx.save();ctx.translate(x+transformState.x*(w/390),y);ctx.rotate(transformState.rotation*Math.PI/180);ctx.scale(transformState.scale,transformState.scale);ctx.translate(-x,-y);ctx.fillStyle=accent;const backdrop=$('#backdrop').value;if(backdrop!=='none'){ctx.save();ctx.fillStyle=backdrop==='solid'?'rgba(0,0,0,.72)':'rgba(0,0,0,.35)';roundedRect(ctx,w*.06,y-base*1.4,w*.88,base*2.8,base*.35);ctx.fill();ctx.restore()}if(effect==='stack'){[-1,0,1].forEach(d=>{const l=doc.lines[i+d];if(!l)return;ctx.fillStyle=d===0?accent:'rgba(255,255,255,.42)';drawTextLine(ctx,l.text,x,y+d*base*1.45,max,d===0?base:base*.62,align,d===0?1:.55,d===0?850:650)})}else if(effect==='karaoke'){ctx.fillStyle='rgba(255,255,255,.30)';drawTextLine(ctx,line.text,x,y,max,base,align,1,850);ctx.save();const clipW=max*p,left=align==='left'?x:align==='right'?x-max:x-max/2;ctx.beginPath();ctx.rect(left,0,clipW,h);ctx.clip();ctx.fillStyle=accent;drawTextLine(ctx,line.text,x,y,max,base,align,1,850);ctx.restore()}else if(effect==='type'){const t=exportText(line.text);ctx.fillStyle=accent;drawTextLine(ctx,t.slice(0,Math.ceil(t.length*p)),x,y,max,base,align,1,800)}else if(effect==='poster'){ctx.fillStyle=accent;drawTextLine(ctx,line.text,x,y,w*.9,base*1.25,align,1,900)}else if(effect==='words'){const words=exportText(line.text).split(/\s+/);ctx.fillStyle=accent;drawTextLine(ctx,words.slice(0,Math.ceil(words.length*p)).join(' '),x,y,max,base,align,1,850)}else{const fade=Math.min(1,p*5)*Math.min(1,(1-p)*5);ctx.fillStyle=accent;drawTextLine(ctx,line.text,x,y,max,base,align,fade,750)}ctx.restore()}
window.drawExportLyrics=drawExportLyrics;
function drawMusicTag(ctx,w,h){ctx.save();ctx.fillStyle='rgba(0,0,0,.42)';roundedRect(ctx,w*.055,h*.89,w*.62,h*.055,h*.0275);ctx.fill();ctx.fillStyle='#fff';ctx.font=`700 ${w*.032}px ${exportFontFamily()}`;ctx.textBaseline='middle';ctx.fillText('♫  '+($('#songName').textContent||'Original audio'),w*.085,h*.917);ctx.restore()}
async function renderFrame(ctx,bg,ms,w,h){ctx.fillStyle='#050505';ctx.fillRect(0,0,w,h);if(bg){if(bg.kind==='video'&&bg.media.readyState>=2)drawFittedMedia(ctx,bg.media,w,h,background.classList.contains('fit-contain')?'contain':'cover');if(bg.kind==='image')drawFittedMedia(ctx,bg.media,w,h,background.classList.contains('fit-contain')?'contain':'cover')}const dim=+$('#dim').value/100;if(dim){ctx.fillStyle=`rgba(0,0,0,${dim})`;ctx.fillRect(0,0,w,h)}drawGradient(ctx,w,h,$('#gradient').value);drawExportLyrics(ctx,ms,w,h);drawMusicTag(ctx,w,h)}
async function recordCanvasStory({quality,startSeconds,seconds,audioFile,backgroundFile}){if(!exportCanvas.captureStream||!window.MediaRecorder)throw new Error('Video export is unavailable in this browser.');const low=$('#lowMemoryExport')?.checked||false,target=low?Math.min(720,quality):quality,fps=low?20:(target>=1080?24:30),w=target,h=Math.round(target*16/9);exportCanvas.width=w;exportCanvas.height=h;const bg=await prepareBackground(backgroundFile),stream=exportCanvas.captureStream(fps),ac=new (window.AudioContext||window.webkitAudioContext)(),dest=ac.createMediaStreamDestination(),buffer=await ac.decodeAudioData((await audioFile.arrayBuffer()).slice(0)),source=ac.createBufferSource();source.buffer=buffer;source.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const mime=supportedRecordingMime();if(!mime)throw new Error('No compatible video encoder is available.');const chunks=[],rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:low?3000000:(target>=1080?9000000:5000000),audioBitsPerSecond:192000});activeRecorder=rec;rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const done=new Promise((r,j)=>{rec.onstop=()=>r(new Blob(chunks,{type:rec.mimeType||mime}));rec.onerror=()=>j(rec.error||new Error('Recording failed'))});rec.start(500);const start=Math.min(startSeconds,buffer.duration-.01),actual=Math.min(seconds,buffer.duration-start);source.start(ac.currentTime+.05,Math.max(0,start),actual);if(bg?.kind==='video'){bg.media.currentTime=Math.min(+$('#videoStart').value||0,Math.max(0,bg.media.duration-.1));await bg.media.play().catch(()=>{})}const began=performance.now();await new Promise((resolve,reject)=>{function frame(now){if(exportAbort)return reject(new Error('Export cancelled'));const elapsed=(now-began)/1000;if(bg?.kind==='video'&&bg.media.duration>0){const desired=((+$('#videoStart').value||0)+elapsed)%bg.media.duration;if(Math.abs(bg.media.currentTime-desired)>.2)bg.media.currentTime=desired}renderFrame(exportCtx,bg,(startSeconds+elapsed)*1000,w,h);exportStatus(`Rendering ${elapsed.toFixed(1)} of ${actual.toFixed(1)}s…`,Math.min(98,elapsed/actual*98));if(elapsed<actual)requestAnimationFrame(frame);else resolve()}requestAnimationFrame(frame)});rec.stop();try{source.stop()}catch{}const blob=await done;stream.getTracks().forEach(t=>t.stop());await ac.close();if(bg){bg.media.pause?.();URL.revokeObjectURL(bg.url)}activeRecorder=null;return blob}
async function downloadOrShare(blob,filename){const type=blob.type||'video/mp4',file=new File([blob],filename,{type});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'LINA: Lyric Video Visualiser'});return}catch(e){if(e?.name==='AbortError')return}}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}
window.downloadOrShare=downloadOrShare;
$('#exportBtn').onclick=()=>{exportAbort=false;exportStatus('Ready',0);$('#exportStart').max=Math.max(0,(audio.duration||0)-.1);exportDialog.showModal()};
$('#cancelExport').onclick=()=>{exportAbort=true;if(activeRecorder?.state!=='inactive')try{activeRecorder.stop()}catch{}};
$('#beginExport').onclick=async()=>{if(!doc.lines.length)return exportStatus('Add lyrics before exporting.');const audioFile=await projectMediaBlob('audio');if(!audioFile)return exportStatus('Add audio before exporting.');const backgroundFile=await projectMediaBlob('background'),quality=+$('#exportQuality').value||1080,startSeconds=Math.max(0,+$('#exportStart').value||0),seconds=Math.max(.1,Math.min(+duration||15,(audio.duration||duration)-startSeconds));try{$('#beginExport').disabled=true;await requestExportWakeLock();if(document.fonts?.ready)await document.fonts.ready;const blob=await recordCanvasStory({quality,startSeconds,seconds,audioFile,backgroundFile}),isMP4=blob.type.includes('mp4'),ext=isMP4?'mp4':'webm',filename=`LINA-${Math.round(seconds)}s-${quality}p.${ext}`;exportStatus(isMP4?'MP4 ready':'Video ready — browser WebM fallback',100);if(typeof recordExportHistory==='function')recordExportHistory(filename,blob.size);await downloadOrShare(blob,filename);exportDialog.close()}catch(e){exportStatus(e.message||String(e))}finally{$('#beginExport').disabled=false;await releaseExportWakeLock()}};
