// Local lyric-file parser for static hosting. Removes dependency on /api/v1/lyrics/parse.
(function(){
'use strict';
const input=document.getElementById('lyricsFile');
if(!input)return;
function notify(msg){if(typeof window.notify==='function')try{return window.notify(msg)}catch{}const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}else alert(msg)}
function timeToMs(min,sec){return Math.round((Number(min)*60+Number(sec))*1000)}
function parseEnhancedWords(text,lineStart){const words=[];const rx=/<(\d{1,3}):(\d{1,2}(?:\.\d{1,3})?)>([^<]*)/g;let m;while((m=rx.exec(text))){const raw=m[3]||'';const clean=raw.trim();if(!clean)continue;words.push({text:clean,start_ms:timeToMs(m[1],m[2])})}for(let i=0;i<words.length;i++){const next=words[i+1]?.start_ms;words[i].duration_ms=Math.max(80,(next??lineStart+2600)-words[i].start_ms)}return words}
function parseLRC(text){const lines=[];let globalOffset=0;const rawLines=String(text||'').replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n');for(const raw of rawLines){const offsetTag=raw.match(/^\s*\[offset\s*:\s*([+-]?\d+)\s*\]\s*$/i);if(offsetTag){globalOffset=Number(offsetTag[1])||0;continue}if(/^\s*\[(ar|ti|al|by|re|ve|length|id):/i.test(raw))continue;const stamps=[...raw.matchAll(/\[(\d{1,3}):(\d{1,2}(?:\.\d{1,3})?)\]/g)];if(!stamps.length)continue;let content=raw.replace(/\[(\d{1,3}):(\d{1,2}(?:\.\d{1,3})?)\]/g,'').trim();if(!content)continue;for(const s of stamps){const start=Math.max(0,timeToMs(s[1],s[2])+globalOffset);const words=parseEnhancedWords(content,start);const plain=content.replace(/<\d{1,3}:\d{1,2}(?:\.\d{1,3})?>/g,'').replace(/\s+/g,' ').trim();if(!plain)continue;lines.push({text:plain,start_ms:start,duration_ms:2600,...(words.length?{words}: {})})}}
lines.sort((a,b)=>a.start_ms-b.start_ms);for(let i=0;i<lines.length;i++){const next=lines[i+1]?.start_ms;lines[i].duration_ms=Math.max(100,(next??lines[i].start_ms+2600)-lines[i].start_ms);if(lines[i].words?.length){for(let w=0;w<lines[i].words.length;w++){const n=lines[i].words[w+1]?.start_ms;lines[i].words[w].duration_ms=Math.max(80,(n??lines[i].start_ms+lines[i].duration_ms)-lines[i].words[w].start_ms)}}}return {format:lines.some(l=>l.words?.length)?'enhanced_lrc':'lrc',lines}}
function parseSRT(text){const blocks=String(text||'').replace(/^\uFEFF/,'').replace(/\r/g,'').trim().split(/\n{2,}/);const lines=[];const t=s=>{const m=s.match(/(\d{1,2}):(\d{2}):(\d{2})[,\.](\d{1,3})/);if(!m)return null;return (+m[1]*3600+ +m[2]*60+ +m[3])*1000+Number(String(m[4]).padEnd(3,'0').slice(0,3))};for(const b of blocks){const a=b.split('\n');const idx=a.findIndex(x=>x.includes('-->'));if(idx<0)continue;const parts=a[idx].split('-->');const start=t(parts[0]),end=t(parts[1]);const copy=a.slice(idx+1).join(' ').replace(/<[^>]+>/g,'').trim();if(start==null||end==null||!copy)continue;lines.push({text:copy,start_ms:start,duration_ms:Math.max(100,end-start)})}return {format:'srt',lines}}
function parseTXT(text){const rows=String(text||'').replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);return {format:'txt',lines:rows.map((text,i)=>({text,start_ms:i*2600,duration_ms:2600}))}}
function parseByName(name,text){const ext=(name.split('.').pop()||'').toLowerCase();if(ext==='lrc')return parseLRC(text);if(ext==='srt')return parseSRT(text);if(ext==='txt')return parseTXT(text);if(/\[\d{1,3}:\d{1,2}(?:\.\d+)?\]/.test(text))return parseLRC(text);if(/-->/.test(text))return parseSRT(text);return parseTXT(text)}
input.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const text=await f.text();const data=parseByName(f.name,text);if(!data.lines.length)throw new Error('No readable lyric lines were found in this file.');original=clone(data);doc=clone(data);offset=0;const off=document.getElementById('offset');if(off)off.value=0;const offLabel=document.getElementById('offsetLabel');if(offLabel)offLabel.textContent='0 ms';const badge=document.getElementById('formatBadge');if(badge)badge.textContent=data.format.replace('_',' ').toUpperCase();renderTimeline();renderAt(audio.currentTime*1000||0);window.__LV_GUARD__?.checkpoint?.('lyrics-file-opened');notify(`${f.name} opened — ${data.lines.length} lyric lines loaded.`)}catch(err){console.error('Local lyric import failed',err);window.__LV_GUARD__?.checkpoint?.('lyrics-import-failed');notify(`Could not open this lyric file: ${err.message||err}`)}};
})();
