// Apple Music LRC Collector + local self-sync generator.
// Primary automated source: LRCLIB. Five backup websites are exposed as fallbacks.
(function(){
const $=s=>document.querySelector(s);
const providers=[
 {name:'LRCLIB',kind:'synced',url:q=>`https://lrclib.net/search/${encodeURIComponent(q)}`},
 {name:'Musixmatch',kind:'synced',url:q=>`https://www.musixmatch.com/search/${encodeURIComponent(q)}`},
 {name:'NetEase Music',kind:'synced',url:q=>`https://music.163.com/#/search/m/?s=${encodeURIComponent(q)}`},
 {name:'Megalobiz',kind:'synced',url:q=>`https://www.megalobiz.com/search/all?qry=${encodeURIComponent(q)}`},
 {name:'Genius',kind:'plain fallback',url:q=>`https://genius.com/search?q=${encodeURIComponent(q)}`}
];
let collectorDialog,plainLines=[],tapTimes=[],tapIndex=0,lastFetchedLRC='';
function fmtLrc(ms){ms=Math.max(0,Math.round(ms));const m=Math.floor(ms/60000),s=(ms%60000)/1000;return `[${String(m).padStart(2,'0')}:${s.toFixed(2).padStart(5,'0')}]`}
function safeName(v){return String(v||'lyrics').replace(/[\\/:*?"<>|]+/g,'-').trim()||'lyrics'}
function downloadText(text,name,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function parseLrcText(text){const rows=[];for(const raw of String(text||'').replace(/\r/g,'').split('\n')){const tags=[...raw.matchAll(/\[(\d+):(\d+(?:\.\d+)?)\]/g)],copy=raw.replace(/\[[^\]]+\]/g,'').trim();for(const t of tags){if(!copy)continue;rows.push({text:copy,start_ms:Math.round((+t[1]*60 + +t[2])*1000),duration_ms:2600})}}rows.sort((a,b)=>a.start_ms-b.start_ms);rows.forEach((x,i)=>x.duration_ms=Math.max(100,(rows[i+1]?.start_ms??x.start_ms+2600)-x.start_ms));return rows}
function importLRC(text,source='collector'){const rows=parseLrcText(text);if(!rows.length)throw new Error('No timestamped LRC lines were found.');doc={format:'lrc',lines:rows,source};original=clone(doc);offset=0;$('#offset').value=0;$('#offsetLabel').textContent='0 ms';$('#formatBadge').textContent='LRC';renderTimeline();renderAt(audio.currentTime*1000);lastFetchedLRC=text;return rows.length}
function setStatus(msg,tone=''){const el=$('#collectorStatus');if(!el)return;el.textContent=msg;el.dataset.tone=tone}
function metadata(){return {url:$('#amCollectorURL').value.trim(),title:$('#collectorTitle').value.trim(),artist:$('#collectorArtist').value.trim(),album:$('#collectorAlbum').value.trim(),duration:+$('#collectorDuration').value||0}}
function appleTrackId(url){try{const u=new URL(url);const q=u.searchParams.get('i');if(q)return q;const m=u.pathname.match(/\/song\/[^/]+\/(\d+)/);return m?.[1]||''}catch{return ''}}
async function lookupAppleMusic(){const url=$('#amCollectorURL').value.trim(),id=appleTrackId(url);if(!id)return setStatus('Paste an Apple Music song link containing a track ID.','error');setStatus('Reading Apple Music track metadata…');try{const r=await fetch(`https://itunes.apple.com/lookup?id=${encodeURIComponent(id)}&entity=song`);if(!r.ok)throw new Error('Metadata lookup failed');const data=await r.json(),x=data.results?.find(v=>v.wrapperType==='track')||data.results?.[0];if(!x)throw new Error('No track metadata found');$('#collectorTitle').value=x.trackName||'';$('#collectorArtist').value=x.artistName||'';$('#collectorAlbum').value=x.collectionName||'';$('#collectorDuration').value=Math.round((x.trackTimeMillis||0)/1000)||'';if($('#metadataAppleMusicURL'))$('#metadataAppleMusicURL').value=x.trackViewUrl||url;setStatus('Apple Music metadata loaded. Ready to find synced lyrics.','ok')}catch(err){setStatus(`Could not read Apple Music metadata automatically: ${err.message}. Enter the fields manually.`,'error')}}
async function fetchLRCLIB(){const m=metadata();if(!m.title||!m.artist)return setStatus('Track title and artist are required.','error');setStatus('Searching LRCLIB for synced lyrics…');const headers={'Lrclib-Client':'Lyric Video Visualier 1.0 (https://github.com/Tezzaaaaaa/lyricvideovisualiser)'};const exact=new URL('https://lrclib.net/api/get');exact.searchParams.set('track_name',m.title);exact.searchParams.set('artist_name',m.artist);if(m.album)exact.searchParams.set('album_name',m.album);if(m.duration)exact.searchParams.set('duration',String(m.duration));let results=[];try{if(m.album&&m.duration){const r=await fetch(exact,{headers});if(r.ok)results=[await r.json()]}if(!results.length){const u=new URL('https://lrclib.net/api/search');u.searchParams.set('track_name',m.title);u.searchParams.set('artist_name',m.artist);if(m.album)u.searchParams.set('album_name',m.album);const r=await fetch(u,{headers});if(!r.ok)throw new Error(`LRCLIB returned ${r.status}`);results=await r.json()}const best=results.find(x=>x.syncedLyrics)||results[0];if(!best?.syncedLyrics)throw new Error('No synced LRC was found');lastFetchedLRC=best.syncedLyrics;$('#collectorPreview').value=best.syncedLyrics;setStatus(`Found synced lyrics on LRCLIB — ${best.trackName||m.title} · ${best.artistName||m.artist}.`,'ok')}catch(err){setStatus(`LRCLIB did not return synced lyrics. Use a backup source below or make the LRC locally. (${err.message})`,'error')}}
function applyFetched(){const text=$('#collectorPreview').value.trim();if(!text)return setStatus('There is no LRC to import yet.','error');try{const n=importLRC(text,'LRCLIB / collector');setStatus(`Imported ${n} timestamped lyric lines into the project.`,'ok');collectorDialog.close()}catch(err){setStatus(err.message,'error')}}
function backupLinks(){const q=[ $('#collectorTitle').value.trim(),$('#collectorArtist').value.trim() ].filter(Boolean).join(' ');const box=$('#collectorBackups');box.innerHTML=providers.map((p,i)=>`<a target="_blank" rel="noopener noreferrer" href="${p.url(q)}"><b>${i+1}. ${p.name}</b><span>${p.kind}</span></a>`).join('')}
function prepareLocalMaker(){plainLines=$('#collectorPlain').value.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);tapTimes=[];tapIndex=0;$('#tapProgress').textContent=plainLines.length?`0 / ${plainLines.length}`:'No lines loaded';$('#tapCurrent').textContent=plainLines[0]||'Paste plain lyrics first';}
function tapLine(){if(!plainLines.length)prepareLocalMaker();if(!plainLines.length)return setStatus('Paste plain lyrics into the local generator first.','error');if(tapIndex>=plainLines.length)return setStatus('All lines already have timestamps.','ok');tapTimes[tapIndex]=Math.max(0,Math.round(audio.currentTime*1000));tapIndex++;$('#tapProgress').textContent=`${tapIndex} / ${plainLines.length}`;$('#tapCurrent').textContent=plainLines[tapIndex]||'Complete — build the LRC';}
function buildTappedLRC(){if(!plainLines.length)prepareLocalMaker();if(!plainLines.length)return setStatus('Paste plain lyrics first.','error');if(tapTimes.length<plainLines.length){const dur=(audio.duration||+$('#collectorDuration').value||Math.max(plainLines.length*2.6,1))*1000;const step=dur/Math.max(plainLines.length,1);for(let i=0;i<plainLines.length;i++)if(!Number.isFinite(tapTimes[i]))tapTimes[i]=Math.round(i*step)}const order=plainLines.map((text,i)=>({text,t:tapTimes[i]})).sort((a,b)=>a.t-b.t);const lrc=order.map(x=>`${fmtLrc(x.t)} ${x.text}`).join('\n');$('#collectorPreview').value=lrc;lastFetchedLRC=lrc;setStatus('Local LRC generated. Review it, then import or download it.','ok')}
function inject(){const tools=document.querySelector('.toptools');if(!tools||document.getElementById('openCollector'))return;const btn=document.createElement('button');btn.id='openCollector';btn.className='pill collector-open';btn.type='button';btn.textContent='⌁ Find / make LRC';tools.insertBefore(btn,tools.querySelector('.circle'));
collectorDialog=document.createElement('dialog');collectorDialog.id='collectorDialog';collectorDialog.className='collector-dialog';collectorDialog.innerHTML=`<form method="dialog" class="collector-shell"><header><div><p class="collector-eyebrow">SUB TOOL</p><h2>Apple Music LRC Collector</h2></div><button value="cancel" class="collector-close" aria-label="Close">×</button></header><p class="collector-intro">Paste an Apple Music song link. We use the link to identify the track, search for synced LRC, then fall back to five lyric websites. If every site fails, the built-in tap-sync maker can create the LRC locally from plain lyrics.</p><section class="collector-section"><h3>1 · Identify the song</h3><label>Apple Music song URL<input id="amCollectorURL" type="url" inputmode="url" placeholder="https://music.apple.com/…"></label><button id="collectorLookup" type="button">Read Apple Music metadata</button><div class="collector-grid"><label>Title<input id="collectorTitle"></label><label>Artist<input id="collectorArtist"></label><label>Album<input id="collectorAlbum"></label><label>Duration (seconds)<input id="collectorDuration" type="number" min="0" step="1"></label></div></section><section class="collector-section"><h3>2 · Automatic synced-LRC search</h3><button id="collectorSearch" type="button" class="collector-primary">Search LRCLIB</button><div id="collectorStatus" class="collector-status">Ready.</div><textarea id="collectorPreview" class="collector-preview" spellcheck="false" placeholder="Synced LRC will appear here…"></textarea><div class="collector-actions"><button id="collectorImport" type="button">Import into project</button><button id="collectorDownload" type="button">Download .lrc</button></div></section><section class="collector-section"><h3>3 · Five backup websites</h3><p class="collector-note">These open the same title + artist search in another source. Availability changes, so the local maker below remains the final fallback.</p><div id="collectorBackups" class="collector-backups"></div></section><section class="collector-section"><h3>4 · Our own LRC maker</h3><p class="collector-note">Paste plain lyrics, play your local audio, and tap once when each lyric line starts. No lyric website is required.</p><textarea id="collectorPlain" class="collector-preview" placeholder="Paste plain lyrics — one line per lyric line"></textarea><div class="collector-actions"><button id="collectorPrepareTap" type="button">Prepare lines</button><button id="collectorTap" type="button" class="collector-primary">Tap current line</button><button id="collectorBuild" type="button">Build LRC</button></div><div class="tap-card"><b id="tapProgress">No lines loaded</b><span id="tapCurrent">Paste plain lyrics first</span></div></section><footer><small>Apple Music links are used only for track identification/metadata. The collector does not bypass Apple Music DRM or extract protected Apple Music audio.</small></footer></form>`;document.body.append(collectorDialog);
btn.onclick=()=>{const current=$('#metadataAppleMusicURL')?.value||'';if(current&&!$('#amCollectorURL').value)$('#amCollectorURL').value=current;backupLinks();collectorDialog.showModal()};$('#collectorLookup').onclick=lookupAppleMusic;$('#collectorSearch').onclick=fetchLRCLIB;$('#collectorImport').onclick=applyFetched;$('#collectorDownload').onclick=()=>{const text=$('#collectorPreview').value.trim();if(!text)return setStatus('No LRC is ready to download.','error');const m=metadata();downloadText(text,`${safeName(`${m.artist} - ${m.title}`)}.lrc`,'text/plain;charset=utf-8')};['collectorTitle','collectorArtist'].forEach(id=>$('#'+id).addEventListener('input',backupLinks));$('#collectorPrepareTap').onclick=prepareLocalMaker;$('#collectorTap').onclick=tapLine;$('#collectorBuild').onclick=buildTappedLRC;backupLinks();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
