// Milestone 6: persistent audio/background blobs and complete project recovery.
const MEDIA_DB='storyLyrics.media.v1';
const MEDIA_STORE='media';
let selectedAudioFile=null,selectedBackgroundFile=null;
function activeProjectID(){let id=localStorage.getItem(ACTIVE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(ACTIVE_KEY,id)}return id}
function openMediaDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(MEDIA_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(MEDIA_STORE)){const store=db.createObjectStore(MEDIA_STORE,{keyPath:'key'});store.createIndex('project_id','project_id')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function putMedia(projectID,kind,file){if(!file)return;const db=await openMediaDB();await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).put({key:`${projectID}:${kind}`,project_id:projectID,kind,name:file.name,type:file.type,size:file.size,updated_at:new Date().toISOString(),blob:file});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();updateStorageUsage()}
async function getMedia(projectID,kind){const db=await openMediaDB();const item=await new Promise((resolve,reject)=>{const req=db.transaction(MEDIA_STORE).objectStore(MEDIA_STORE).get(`${projectID}:${kind}`);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return item}
async function deleteProjectMedia(projectID){const db=await openMediaDB();await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite'),idx=tx.objectStore(MEDIA_STORE).index('project_id'),req=idx.openCursor(IDBKeyRange.only(projectID));req.onsuccess=()=>{const c=req.result;if(c){c.delete();c.continue()}};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();updateStorageUsage()}
async function updateStorageUsage(){const label=$('#storageUsage');if(!label)return;try{if(navigator.storage?.estimate){const e=await navigator.storage.estimate(),used=e.usage||0,quota=e.quota||0;label.textContent=`${formatBytes(used)} of ${formatBytes(quota)}`}else label.textContent='Available'}catch{label.textContent='Unavailable'}}
function formatBytes(n){if(!n)return'0 MB';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i<2?0:1)} ${u[i]}`}
function setAudioFromStored(item){if(!item?.blob)return;selectedAudioFile=new File([item.blob],item.name||'audio',{type:item.type||item.blob.type});if(audio.src?.startsWith('blob:'))URL.revokeObjectURL(audio.src);audio.src=URL.createObjectURL(item.blob);$('#songName').textContent=(item.name||'Original audio').replace(/\.[^.]+$/,'');audio.onloadedmetadata=()=>$('#scrubber').max=Math.min(duration,audio.duration||duration)}
function setBackgroundFromStored(item){if(!item?.blob)return;selectedBackgroundFile=new File([item.blob],item.name||'background',{type:item.type||item.blob.type});if(backgroundURL)URL.revokeObjectURL(backgroundURL);backgroundURL=URL.createObjectURL(item.blob);background.innerHTML='';background.style.backgroundImage='none';backgroundVideo=null;if((item.type||'').startsWith('video/')){const v=document.createElement('video');backgroundVideo=v;v.src=backgroundURL;v.autoplay=true;v.loop=true;v.muted=true;v.playsInline=true;v.onloadedmetadata=()=>{$('#videoStart').max=Math.max(0,v.duration-.1);v.currentTime=0};background.append(v);v.play().catch(()=>{})}else background.style.backgroundImage=`url("${backgroundURL}")`}
async function restoreProjectMedia(projectID){const [a,b]=await Promise.all([getMedia(projectID,'audio'),getMedia(projectID,'background')]);if(a)setAudioFromStored(a);if(b)setBackgroundFromStored(b);if(a||b)notify('Project and media restored')}
$('#audioFile').addEventListener('change',e=>{selectedAudioFile=e.target.files?.[0]||null;if(selectedAudioFile)putMedia(activeProjectID(),'audio',selectedAudioFile).catch(()=>notify('Audio could not be stored'))});
$('#backgroundFile').addEventListener('change',e=>{selectedBackgroundFile=e.target.files?.[0]||null;if(selectedBackgroundFile)putMedia(activeProjectID(),'background',selectedBackgroundFile).catch(()=>notify('Background could not be stored'))});
const baseSaveCurrentProject=saveCurrentProject;saveCurrentProject=function(silent=false){baseSaveCurrentProject(silent);const id=activeProjectID();if(selectedAudioFile)putMedia(id,'audio',selectedAudioFile).catch(()=>{});if(selectedBackgroundFile)putMedia(id,'background',selectedBackgroundFile).catch(()=>{})};
const baseLoadProject=loadProject;loadProject=function(id){baseLoadProject(id);restoreProjectMedia(id).catch(()=>notify('Saved media could not be restored'))};
const baseNewProject=newProject;newProject=function(){baseNewProject();selectedAudioFile=null;selectedBackgroundFile=null;audio.removeAttribute('src');audio.load();background.innerHTML='';background.style.backgroundImage='';$('#songName').textContent='Original audio'};
$('#clearProjectMedia').addEventListener('click',async()=>{const id=localStorage.getItem(ACTIVE_KEY);if(!id)return notify('No current project');await deleteProjectMedia(id);audio.removeAttribute('src');audio.load();background.innerHTML='';background.style.backgroundImage='';notify('Current project media removed')});
window.addEventListener('load',()=>{updateStorageUsage();const id=localStorage.getItem(ACTIVE_KEY);if(id&&savedProjects().some(p=>p.id===id))loadProject(id);else if(id)restoreProjectMedia(id).catch(()=>{})});
