// Milestone 10: onboarding, complete user flow, project management, export history and diagnostics.
const ONBOARDING_KEY='storyLyrics.onboarding.v10';
const EXPORT_HISTORY_KEY='storyLyrics.exports.v1';
const EXPORT_METADATA_KEY='lyricVideoVisualier.exportMetadata.v1';
function showOnboarding(){const o=$('#onboarding');o.classList.remove('hidden');o.setAttribute('aria-hidden','false')}
function hideOnboarding(){const o=$('#onboarding');o.classList.add('hidden');o.setAttribute('aria-hidden','true');localStorage.setItem(ONBOARDING_KEY,'done')}
$('#startCreating').onclick=hideOnboarding;$('#closeOnboarding').onclick=hideOnboarding;
if(!localStorage.getItem(ONBOARDING_KEY))setTimeout(showOnboarding,250);
function flowState(){return {audio:!!(selectedAudioFile||audio.src),lyrics:!!doc.lines.length,style:!!effect,export:!!(selectedAudioFile||audio.src)&&!!doc.lines.length}}
function updateFlowStatus(){const st=flowState();document.querySelectorAll('[data-flow]').forEach(el=>el.classList.toggle('complete',!!st[el.dataset.flow]));const exportBtn=$('#exportBtn');exportBtn.classList.toggle('needs-input',!st.export);exportBtn.title=st.export?'Export Story MP4':'Add a song and lyrics first'}
document.addEventListener('change',()=>setTimeout(updateFlowStatus,30));document.addEventListener('input',()=>setTimeout(updateFlowStatus,30));
const oldRenderAt=renderAt;renderAt=function(ms){oldRenderAt(ms);updateFlowStatus()};
function duplicateCurrentProject(){const p=projectSnapshot();p.id=crypto.randomUUID();p.name=(p.name||'Untitled Story')+' Copy';p.updated_at=new Date().toISOString();const items=savedProjects();items.unshift(p);writeProjects(items.slice(0,30));localStorage.setItem(ACTIVE_KEY,p.id);$('#projectName').value=p.name;renderSavedProjects();notify('Project duplicated')}
async function deleteCurrentProject(){const id=localStorage.getItem(ACTIVE_KEY);if(!id)return notify('No saved project selected');if(!confirm('Delete this project and its stored media?'))return;writeProjects(savedProjects().filter(p=>p.id!==id));await deleteProjectMedia(id).catch(()=>{});localStorage.removeItem(ACTIVE_KEY);newProject();renderSavedProjects();notify('Project deleted')}
$('#duplicateProject').onclick=duplicateCurrentProject;$('#deleteProject').onclick=deleteCurrentProject;
const oldRenderSavedProjects=renderSavedProjects;renderSavedProjects=function(){const box=$('#savedProjects'),items=savedProjects();box.innerHTML=items.length?items.map(p=>`<article class="saved-project-row"><button class="saved-project" data-open-project="${p.id}"><span><b>${esc(p.name)}</b><small>${new Date(p.updated_at).toLocaleString()}</small></span><span>Open</span></button><button class="project-row-delete" data-delete-project="${p.id}" aria-label="Delete ${esc(p.name)}">×</button></article>`).join(''):'<p class="hint">No saved projects on this device yet.</p>'};
$('#savedProjects').addEventListener('click',async e=>{const d=e.target.closest('[data-delete-project]');if(!d)return;e.stopPropagation();if(!confirm('Delete this saved project?'))return;writeProjects(savedProjects().filter(p=>p.id!==d.dataset.deleteProject));await deleteProjectMedia(d.dataset.deleteProject).catch(()=>{});renderSavedProjects();notify('Saved project deleted')});
function exportsHistory(){try{return JSON.parse(localStorage.getItem(EXPORT_HISTORY_KEY)||'[]')}catch{return[]}}
function currentExportMetadata(filename=''){let saved={};try{saved=JSON.parse(localStorage.getItem(EXPORT_METADATA_KEY)||'{}')}catch{}const song=($('#songName')?.textContent||'').trim();const project=($('#projectName')?.value||'Untitled Story').trim();const pageUrl=location.href;return {schema:'https://schema.org/VideoObject',schema_version:'1.0',generator:'Lyric Video Visualier',generator_version:'2026.08',project_name:project,file_name:filename||'',title:(saved.title||song||project).trim(),artist:(saved.artist||'').trim(),album:(saved.album||'').trim(),isrc:(saved.isrc||'').trim(),apple_music_url:(saved.appleMusicUrl||'').trim(),source_website:(saved.websiteUrl||pageUrl).trim(),source_page:pageUrl,content_type:'lyric video visualisation',sharing_context:'Apple Music content sharing',lyrics_format:($('#formatBadge')?.textContent||'').trim(),lyric_effect:effect||'',duration_seconds:Number(duration||0),aspect_ratio:'9:16',language:(document.documentElement.lang||'en'),created_at:new Date().toISOString(),copyright_notice:'User-supplied media. Rights remain with their respective owners.',usage_note:'Created for personal/social sharing. Apple Music links identify the referenced track and do not embed or redistribute Apple Music audio.',software:'Lyric Video Visualier web app',website_name:'Lyric Video Visualier',website_url:(saved.websiteUrl||pageUrl).trim(),apple_music:{content_url:(saved.appleMusicUrl||'').trim(),track:saved.title||song||'',artist:saved.artist||'',album:saved.album||'',isrc:saved.isrc||'',share_attribution:'Apple Music'},technical:{export_format:'MP4',visualiser:'HTML Canvas',timing_source:($('#formatBadge')?.textContent||'').trim(),effect:effect||'',uppercase_mode:document.querySelector('#letterCase')?.value||'original'}}}
function saveMetadataFields(){const data={title:$('#metaTitle')?.value||'',artist:$('#metaArtist')?.value||'',album:$('#metaAlbum')?.value||'',isrc:$('#metaISRC')?.value||'',appleMusicUrl:$('#metaAppleMusic')?.value||'',websiteUrl:$('#metaWebsite')?.value||''};localStorage.setItem(EXPORT_METADATA_KEY,JSON.stringify(data))}
function installMetadataPanel(){const projectPanel=document.querySelector('[data-panel-content="project"]');if(!projectPanel||$('#exportMetadataPanel'))return;let saved={};try{saved=JSON.parse(localStorage.getItem(EXPORT_METADATA_KEY)||'{}')}catch{}const box=document.createElement('div');box.id='exportMetadataPanel';box.className='project-subsection';box.innerHTML=`<h3>Export metadata</h3><div class="grid"><label>Track title<input id="metaTitle" type="text" value="${esc(saved.title||'')}"></label><label>Artist<input id="metaArtist" type="text" value="${esc(saved.artist||'')}"></label><label>Album<input id="metaAlbum" type="text" value="${esc(saved.album||'')}"></label><label>ISRC<input id="metaISRC" type="text" value="${esc(saved.isrc||'')}"></label><label style="grid-column:1/-1">Apple Music share URL<input id="metaAppleMusic" type="text" inputmode="url" placeholder="https://music.apple.com/..." value="${esc(saved.appleMusicUrl||'')}"></label><label style="grid-column:1/-1">Website URL<input id="metaWebsite" type="text" inputmode="url" value="${esc(saved.websiteUrl||location.href)}"></label></div><p class="hint">Stored with export history and used for rich share text plus a machine-readable metadata sidecar.</p>`;projectPanel.append(box);box.addEventListener('input',saveMetadataFields)}
function metadataSidecar(metadata,filename){const clean=(filename||'Lyric-Video-Visualier').replace(/\.[^.]+$/,'');return new File([JSON.stringify(metadata,null,2)],`${clean}.metadata.json`,{type:'application/json'})}
function richShareText(metadata){const parts=[];if(metadata.title)parts.push(metadata.title);if(metadata.artist)parts.push(`— ${metadata.artist}`);if(metadata.apple_music_url)parts.push(`Apple Music: ${metadata.apple_music_url}`);if(metadata.source_website)parts.push(`Created with Lyric Video Visualier: ${metadata.source_website}`);return parts.join(' ')}
function downloadSidecar(file){const u=URL.createObjectURL(file),a=document.createElement('a');a.href=u;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
function recordExportHistory(filename,bytes){const meta=currentExportMetadata(filename),items=exportsHistory();items.unshift({id:crypto.randomUUID(),filename,bytes,project:$('#projectName').value.trim()||'Untitled Story',created_at:new Date().toISOString(),duration,metadata:meta});localStorage.setItem(EXPORT_HISTORY_KEY,JSON.stringify(items.slice(0,20)));renderExportHistory()}
function renderExportHistory(){const box=$('#exportHistory'),items=exportsHistory();box.innerHTML=items.length?items.map(x=>`<div class="export-history-row"><span><b>${esc(x.project)}</b><small>${new Date(x.created_at).toLocaleString()} · ${x.duration}s · ${formatBytes(x.bytes||0)}${x.metadata?.artist?` · ${esc(x.metadata.artist)}`:''}${x.metadata?.apple_music_url?' · Apple Music linked':''}</small></span><span>MP4</span></div>`).join(''):'<p class="hint">Completed exports will appear here.</p>'}
async function renderDiagnostics(){const box=$('#diagnostics');box.innerHTML='<span>Checking…</span>';let health={};try{health=await fetch('/api/v1/health').then(r=>r.json())}catch{}let estimate={};try{estimate=await navigator.storage?.estimate?.()||{}}catch{}const rows=[['Website',navigator.onLine?'Online':'Offline'],['Backend',health.status==='ok'?`Connected · ${health.version||''}`:'Not connected'],['FFmpeg',health.ffmpeg?'Ready':'Not detected'],['PWA',window.matchMedia('(display-mode: standalone)').matches?'Installed':'Safari website'],['Project storage',`${formatBytes(estimate.usage||0)} used`],['Browser',/iphone|ipad|ipod/i.test(navigator.userAgent)?'iPhone/iPad Safari-compatible':'Desktop browser']];box.innerHTML=rows.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('')}
$('#refreshDiagnostics').onclick=renderDiagnostics;
window.addEventListener('online',renderDiagnostics);window.addEventListener('offline',renderDiagnostics);

// Enrich the existing export/share handoff without changing media pixels or lyric timing.
if(typeof downloadOrShare==='function'){const originalDownloadOrShare=downloadOrShare;downloadOrShare=async function(fileBlob,filename){const metadata=currentExportMetadata(filename),videoFile=new File([fileBlob],filename,{type:'video/mp4'}),sidecar=metadataSidecar(metadata,filename),shareData={files:[videoFile],title:metadata.title?`${metadata.title}${metadata.artist?` — ${metadata.artist}`:''}`:'Lyric Video Visualier export',text:richShareText(metadata)};if(metadata.apple_music_url)shareData.url=metadata.apple_music_url;else if(metadata.source_website)shareData.url=metadata.source_website;if(navigator.canShare?.({files:[videoFile]})){try{await navigator.share(shareData);return}catch(err){if(err?.name!=='AbortError')console.warn('Rich share failed; falling back to download',err)}}await originalDownloadOrShare(fileBlob,filename);downloadSidecar(sidecar)}}

installMetadataPanel();
renderSavedProjects();renderExportHistory();renderDiagnostics();updateFlowStatus();
