// Milestone 10: onboarding, complete user flow, project management, export history and diagnostics.
const ONBOARDING_KEY='storyLyrics.onboarding.v10';
const EXPORT_HISTORY_KEY='storyLyrics.exports.v1';
function showOnboarding(){const o=$('#onboarding');o.classList.remove('hidden');o.setAttribute('aria-hidden','false')}
function hideOnboarding(){const o=$('#onboarding');o.classList.add('hidden');o.setAttribute('aria-hidden','true');localStorage.setItem(ONBOARDING_KEY,'done')}
$('#startCreating').onclick=hideOnboarding;$('#closeOnboarding').onclick=hideOnboarding;
if(!localStorage.getItem(ONBOARDING_KEY))setTimeout(showOnboarding,250);
function flowState(){return {audio:!!(selectedAudioFile||audio.src),lyrics:!!doc.lines.length,style:!!effect,export:!!(selectedAudioFile||audio.src)&&!!doc.lines.length}}
function updateFlowStatus(){const st=flowState();document.querySelectorAll('[data-flow]').forEach(el=>el.classList.toggle('complete',!!st[el.dataset.flow]));const exportBtn=$('#exportBtn');exportBtn.classList.toggle('needs-input',!st.export);exportBtn.title=st.export?'Export Story MP4':'Add a song and lyrics first'}
document.addEventListener('change',()=>setTimeout(updateFlowStatus,30));document.addEventListener('input',()=>setTimeout(updateFlowStatus,30));
const oldRenderAt=renderAt;renderAt=function(ms){oldRenderAt(ms);updateFlowStatus()};
function duplicateCurrentProject(){const p=projectSnapshot();p.id=crypto.randomUUID();p.name=(p.name||'Untitled Story')+' Copy';p.updated_at=new Date().toISOString();const items=savedProjects();items.unshift(p);writeProjects(items.slice(0,30));localStorage.setItem(ACTIVE_KEY,p.id);$('#projectName').value=p.name;renderSavedProjects();notify('Project duplicated')}
async function deleteCurrentProject(){const id=localStorage.getItem(ACTIVE_KEY);if(!id)return notify('No saved project selected');if(!confirm('Delete this project and its stored media?'))return;writeProjects(savedProjects().filter(p=>p.id!==id));await deleteProjectMedia(id).catch(()=>{});localStorage.removeItem(ACTIVE_KEY);newProject();renderSavedProjects();notify('Project deleted')}
$('#duplicateProject').onclick=duplicateCurrentProject;$('#deleteProject').onclick=deleteCurrentProject;
const oldRenderSavedProjects=renderSavedProjects;renderSavedProjects=function(){const box=$('#savedProjects'),items=savedProjects();box.innerHTML=items.length?items.map(p=>`<article class="saved-project-row"><button class="saved-project" data-open-project="${p.id}"><span><b>${esc(p.name)}</b><small>${new Date(p.updated_at).toLocaleString()}</small></span><span>Open</span></button><button class="project-row-delete" data-delete-project="${p.id}" aria-label="Delete ${esc(p.name)}">×</button></article>`).join(''):'<p class="hint">No saved projects on this device yet.</p>'};
$('#savedProjects').addEventListener('click',async e=>{const d=e.target.closest('[data-delete-project]');if(!d)return;e.stopPropagation();if(!confirm('Delete this saved project?'))return;writeProjects(savedProjects().filter(p=>p.id!==d.dataset.deleteProject));await deleteProjectMedia(d.dataset.deleteProject).catch(()=>{});renderSavedProjects();notify('Saved project deleted')});
function exportsHistory(){try{return JSON.parse(localStorage.getItem(EXPORT_HISTORY_KEY)||'[]')}catch{return[]}}
function recordExportHistory(filename,bytes){const items=exportsHistory();items.unshift({id:crypto.randomUUID(),filename,bytes,project:$('#projectName').value.trim()||'Untitled Story',created_at:new Date().toISOString(),duration});localStorage.setItem(EXPORT_HISTORY_KEY,JSON.stringify(items.slice(0,20)));renderExportHistory()}
function renderExportHistory(){const box=$('#exportHistory'),items=exportsHistory();box.innerHTML=items.length?items.map(x=>`<div class="export-history-row"><span><b>${esc(x.project)}</b><small>${new Date(x.created_at).toLocaleString()} · ${x.duration}s · ${formatBytes(x.bytes||0)}</small></span><span>MP4</span></div>`).join(''):'<p class="hint">Completed exports will appear here.</p>'}
async function renderDiagnostics(){const box=$('#diagnostics');box.innerHTML='<span>Checking…</span>';let health={};try{health=await fetch('/api/v1/health').then(r=>r.json())}catch{}let estimate={};try{estimate=await navigator.storage?.estimate?.()||{}}catch{}const rows=[['Website',navigator.onLine?'Online':'Offline'],['Backend',health.status==='ok'?`Connected · ${health.version||''}`:'Not connected'],['FFmpeg',health.ffmpeg?'Ready':'Not detected'],['PWA',window.matchMedia('(display-mode: standalone)').matches?'Installed':'Safari website'],['Project storage',`${formatBytes(estimate.usage||0)} used`],['Browser',/iphone|ipad|ipod/i.test(navigator.userAgent)?'iPhone/iPad Safari-compatible':'Desktop browser']];box.innerHTML=rows.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('')}
$('#refreshDiagnostics').onclick=renderDiagnostics;
window.addEventListener('online',renderDiagnostics);window.addEventListener('offline',renderDiagnostics);
renderSavedProjects();renderExportHistory();renderDiagnostics();updateFlowStatus();
