// Lyric Video Visualier — site-wide fail-safe guardrail layer.
// Designed to fail closed, preserve user work, and provide a recoverable path at every stage.
(function(){
'use strict';
const $=s=>document.querySelector(s);
const LOG_KEY='lyricVisualier.guard.log.v1',CHECKPOINT_KEY='lyricVisualier.guard.checkpoint.v1';
const LIMITS={audio:1024*1024*1024,background:750*1024*1024,lyrics:2*1024*1024,maxDuration:60*60};
const required=['audioFile','lyricsFile','backgroundFile','lyricsLayer','story','scrubber','exportBtn','projectName'];
let status={startup:false,storage:false,media:false,lyrics:false,export:false,network:navigator.onLine};
function now(){return new Date().toISOString()}
function log(stage,message,detail=''){try{const rows=JSON.parse(sessionStorage.getItem(LOG_KEY)||'[]');rows.unshift({at:now(),stage,message,detail:String(detail||'').slice(0,1000)});sessionStorage.setItem(LOG_KEY,JSON.stringify(rows.slice(0,100)))}catch{}console.warn(`[LV:${stage}]`,message,detail||'')}
function notifyGuard(message){if(typeof window.notify==='function')try{return window.notify(message)}catch{}const t=$('#toast');if(t){t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}}
function storageTest(){try{const k='__lv_test__';localStorage.setItem(k,'1');localStorage.removeItem(k);status.storage=true;return true}catch(e){status.storage=false;log('storage','Persistent storage unavailable',e);return false}}
function checkpoint(reason='automatic'){try{const snapshot={at:now(),reason,project:$('#projectName')?.value||'Untitled Video',audioName:$('#audioFile')?.files?.[0]?.name||'',lyricsName:$('#lyricsFile')?.files?.[0]?.name||'',effect:typeof effect!=='undefined'?effect:null,duration:typeof duration!=='undefined'?duration:null,offset:typeof offset!=='undefined'?offset:null,selected:typeof selected!=='undefined'?selected:null,doc:typeof doc!=='undefined'?JSON.parse(JSON.stringify(doc)):null};sessionStorage.setItem(CHECKPOINT_KEY,JSON.stringify(snapshot));return true}catch(e){log('checkpoint','Could not save recovery checkpoint',e);return false}}
function startupCheck(){const missing=required.filter(id=>!document.getElementById(id));if(missing.length){log('startup','Critical UI elements missing',missing.join(','));notifyGuard('Some app controls failed to load. Reload before starting a project.');return false}status.startup=true;storageTest();checkpoint('startup');return true}
function validateFile(file,kind){if(!file)return {ok:false,error:'No file selected.'};if(file.size<=0)return {ok:false,error:'The selected file is empty.'};const max=LIMITS[kind]||LIMITS.lyrics;if(file.size>max)return {ok:false,error:`${kind} file is too large for safe browser processing.`};if(kind==='audio'&&!file.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|wav|flac|ogg|opus)$/i.test(file.name))return {ok:false,error:'Unsupported audio format.'};if(kind==='background'&&!file.type.startsWith('image/')&&!file.type.startsWith('video/'))return {ok:false,error:'Background must be an image or video.'};if(kind==='lyrics'&&!/\.(txt|lrc|srt)$/i.test(file.name))return {ok:false,error:'Lyrics must be TXT, LRC or SRT.'};return {ok:true}}
function guardInput(id,kind){const input=$('#'+id);if(!input)return;input.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const v=validateFile(f,kind);if(!v.ok){log(kind,'File rejected',v.error);e.target.value='';notifyGuard(v.error);return}checkpoint(`${kind}-selected`);if(kind==='media'||kind==='audio')status.media=true},{capture:true})}
function lyricSanity(){try{if(typeof doc==='undefined'||!Array.isArray(doc.lines))return false;if(!doc.lines.length)return false;if(doc.lines.length>5000){log('lyrics','Too many lyric lines',doc.lines.length);return false}let last=-1;for(const l of doc.lines){if(!l||typeof l.text!=='string'||!Number.isFinite(+l.start_ms)||+l.start_ms<0)return false;if(+l.start_ms<last)log('lyrics','Non-monotonic lyric timing detected',`${last} -> ${l.start_ms}`);last=Math.max(last,+l.start_ms)}status.lyrics=true;return true}catch(e){log('lyrics','Lyric sanity check threw',e);return false}}
function estimateStorage(){return navigator.storage?.estimate?.().catch(()=>null)||Promise.resolve(null)}
async function exportPreflight(){const problems=[];try{if(typeof doc==='undefined'||!doc.lines?.length)problems.push('Add or generate lyrics first.');else if(!lyricSanity())problems.push('Lyrics failed the integrity check.');const af=window.selectedAudioFile||$('#audioFile')?.files?.[0];if(!af&&!$('#audio')?.src)problems.push('Add audio first.');if(af){const v=validateFile(af,'audio');if(!v.ok)problems.push(v.error)}if(!window.MediaRecorder)problems.push('This browser does not support MediaRecorder.');if(!HTMLCanvasElement.prototype.captureStream)problems.push('This browser cannot capture the export canvas.');const est=await estimateStorage();if(est?.quota&&est?.usage&&est.quota-est.usage<100*1024*1024)problems.push('Less than 100 MB browser storage remains. Free space before exporting.');if(!navigator.onLine)log('export','Offline export requested','Local rendering may work; server MP4 conversion may not.');if(problems.length){log('export','Preflight blocked export',problems.join(' | '));notifyGuard(problems[0]);return false}checkpoint('pre-export');status.export=true;return true}catch(e){log('export','Preflight failed unexpectedly',e);notifyGuard('Export preflight failed safely. Your project was not changed.');return false}}
function installExportGate(){const btn=$('#exportBtn');if(!btn)return;btn.addEventListener('click',async e=>{const ok=await exportPreflight();if(!ok){e.preventDefault();e.stopImmediatePropagation()}},true);const begin=$('#beginExport');if(begin)begin.addEventListener('click',async e=>{const ok=await exportPreflight();if(!ok){e.preventDefault();e.stopImmediatePropagation()}},true)}
function mediaRuntimeGuards(){const audio=$('#audio');if(!audio)return;audio.addEventListener('error',()=>{log('audio','Browser could not decode audio',audio.error?.message||audio.error?.code);notifyGuard('Audio could not be decoded. Try MP3, M4A, AAC or WAV.')});audio.addEventListener('loadedmetadata',()=>{if(!Number.isFinite(audio.duration)||audio.duration<=0){log('audio','Invalid duration',audio.duration);notifyGuard('Audio duration could not be read.')}else if(audio.duration>LIMITS.maxDuration){log('audio','Very long audio loaded',audio.duration);notifyGuard('This audio is unusually long; shorter media is safer for browser export.')}checkpoint('audio-ready')})}
function networkGuards(){window.addEventListener('online',()=>{status.network=true;notifyGuard('Connection restored. Online lyric sources are available again.')});window.addEventListener('offline',()=>{status.network=false;log('network','Browser went offline');notifyGuard('Offline mode: existing projects and the local LRC maker still work.')})}
function globalErrorGuards(){window.addEventListener('error',e=>{log('runtime',e.message||'Unhandled error',`${e.filename||''}:${e.lineno||''}`);checkpoint('runtime-error')});window.addEventListener('unhandledrejection',e=>{log('promise','Unhandled promise rejection',e.reason?.message||e.reason);checkpoint('promise-error')});window.addEventListener('pagehide',()=>checkpoint('pagehide'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')checkpoint('backgrounded')})}
function protectNavigation(){window.addEventListener('beforeunload',()=>checkpoint('beforeunload'))}
function expose(){window.__LV_GUARD__={status,checkpoint,exportPreflight,lyricSanity,validateFile,logs:()=>{try{return JSON.parse(sessionStorage.getItem(LOG_KEY)||'[]')}catch{return[]}},recovery:()=>{try{return JSON.parse(sessionStorage.getItem(CHECKPOINT_KEY)||'null')}catch{return null}}}}
function init(){startupCheck();guardInput('audioFile','audio');guardInput('lyricsFile','lyrics');guardInput('backgroundFile','background');installExportGate();mediaRuntimeGuards();networkGuards();globalErrorGuards();protectNavigation();expose();setInterval(()=>checkpoint('periodic'),30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
