// Lyric Video Visualier — site-wide fail-safe guardrail layer.
// Fails closed where corruption is possible, preserves work, and self-recovers where safe.
(function(){
'use strict';
const $=s=>document.querySelector(s);
const LOG_KEY='lyricVisualier.guard.log.v2',CHECKPOINT_KEY='lyricVisualier.guard.checkpoint.v2';
const LIMITS={audio:1024*1024*1024,background:750*1024*1024,lyrics:2*1024*1024,maxDuration:60*60};
const required=['audioFile','lyricsFile','backgroundFile','lyricsLayer','story','scrubber','exportBtn','projectName','fontStyle','exportCanvas'];
let status={startup:false,storage:false,media:false,lyrics:false,export:false,network:navigator.onLine,sync:true,font:true};
let sync={lastAudioMs:0,lastPerf:performance.now(),lastRepair:0,seeking:false,stallCount:0};
let exportWatch={active:false,lastProgress:0,lastChange:0,timer:0};
function now(){return new Date().toISOString()}
function log(stage,message,detail=''){try{const rows=JSON.parse(sessionStorage.getItem(LOG_KEY)||'[]');rows.unshift({at:now(),stage,message,detail:String(detail||'').slice(0,1500)});sessionStorage.setItem(LOG_KEY,JSON.stringify(rows.slice(0,150)))}catch{}console.warn(`[LV:${stage}]`,message,detail||'')}
function notifyGuard(message){if(typeof window.notify==='function')try{return window.notify(message)}catch{}const t=$('#toast');if(t){t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}}
function storageTest(){try{const k='__lv_test__';localStorage.setItem(k,'1');localStorage.removeItem(k);status.storage=true;return true}catch(e){status.storage=false;log('storage','Persistent storage unavailable',e);return false}}
function checkpoint(reason='automatic'){try{const snapshot={at:now(),reason,project:$('#projectName')?.value||'Untitled Video',audioName:$('#audioFile')?.files?.[0]?.name||'',lyricsName:$('#lyricsFile')?.files?.[0]?.name||'',font:$('#fontStyle')?.value||'',effect:typeof effect!=='undefined'?effect:null,duration:typeof duration!=='undefined'?duration:null,offset:typeof offset!=='undefined'?offset:null,selected:typeof selected!=='undefined'?selected:null,audioTime:$('#audio')?.currentTime||0,doc:typeof doc!=='undefined'?JSON.parse(JSON.stringify(doc)):null};sessionStorage.setItem(CHECKPOINT_KEY,JSON.stringify(snapshot));return true}catch(e){log('checkpoint','Could not save recovery checkpoint',e);return false}}
function startupCheck(){const missing=required.filter(id=>!document.getElementById(id));if(missing.length){log('startup','Critical UI elements missing',missing.join(','));notifyGuard('Some app controls failed to load. Reload before starting a project.');return false}status.startup=true;storageTest();checkpoint('startup');return true}
function validateFile(file,kind){if(!file)return {ok:false,error:'No file selected.'};if(file.size<=0)return {ok:false,error:'The selected file is empty.'};const max=LIMITS[kind]||LIMITS.lyrics;if(file.size>max)return {ok:false,error:`${kind} file is too large for safe browser processing.`};if(kind==='audio'&&!file.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|wav|flac|ogg|opus)$/i.test(file.name))return {ok:false,error:'Unsupported audio format.'};if(kind==='background'&&!file.type.startsWith('image/')&&!file.type.startsWith('video/'))return {ok:false,error:'Background must be an image or video.'};if(kind==='lyrics'&&!/\.(txt|lrc|srt|vtt)$/i.test(file.name))return {ok:false,error:'Lyrics must be TXT, LRC, SRT or VTT.'};return {ok:true}}
function guardInput(id,kind){const input=$('#'+id);if(!input)return;input.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const v=validateFile(f,kind);if(!v.ok){log(kind,'File rejected',v.error);e.target.value='';notifyGuard(v.error);return}checkpoint(`${kind}-selected`);if(kind==='audio')status.media=true},{capture:true})}
function lyricSanity(){try{if(typeof doc==='undefined'||!Array.isArray(doc.lines)||!doc.lines.length)return false;if(doc.lines.length>5000){log('lyrics','Too many lyric lines',doc.lines.length);return false}let last=-1;for(const [i,l] of doc.lines.entries()){if(!l||typeof l.text!=='string'||!l.text.trim()||!Number.isFinite(+l.start_ms)||+l.start_ms<0)return false;if(+l.start_ms<last){log('lyrics','Non-monotonic lyric timing detected',`${last} -> ${l.start_ms}`);return false}last=+l.start_ms;if(Array.isArray(l.words)){let wl=-1;for(const w of l.words){if(!w||typeof w.text!=='string'||!Number.isFinite(+w.start_ms)||+w.start_ms<wl){log('sync','Invalid enhanced-LRC word timing',`line ${i}`);return false}wl=+w.start_ms}}}status.lyrics=true;return true}catch(e){log('lyrics','Lyric sanity check threw',e);return false}}
function estimateStorage(){return navigator.storage?.estimate?.().catch(()=>null)||Promise.resolve(null)}
function canvasSanity(){try{const c=$('#exportCanvas'),ctx=c?.getContext?.('2d');if(!c||!ctx)return false;ctx.save();ctx.font='800 48px "Helvetica Neue", Helvetica, Arial, sans-serif';const m=ctx.measureText('LYRIC VIDEO VISUALIER');ctx.restore();return Number.isFinite(m.width)&&m.width>0}catch(e){log('export','Canvas text test failed',e);return false}}
function injectHelvetica(){const theme=document.querySelector('link[data-lv-helvetica-theme]');if(!theme){const link=document.createElement('link');link.rel='stylesheet';link.href='helvetica_theme.css';link.dataset.lvHelveticaTheme='1';document.head.append(link)}const select=$('#fontStyle');if(!select)return;let opt=select.querySelector('option[value="helvetica"]');if(!opt){opt=document.createElement('option');opt.value='helvetica';opt.textContent='Helvetica';const first=select.options[0];first?.insertAdjacentElement('afterend',opt)}else if(select.options[1]!==opt){select.insertBefore(opt,select.options[1]||null)}if(!select.dataset.lvOfficialDefault){select.dataset.lvOfficialDefault='1';select.value='helvetica';setTimeout(()=>select.dispatchEvent(new Event('change',{bubbles:true})),0)}document.documentElement.classList.add('lv-helvetica-site')}
async function fontSanity({notify=false}={}){const select=$('#fontStyle'),layer=$('#lyricsLayer');if(!select||!layer)return false;const choice=select.value;const stacks={rounded:'-apple-system,BlinkMacSystemFont,"Arial Rounded MT Bold",Arial,sans-serif',helvetica:'"Helvetica Neue",Helvetica,Arial,sans-serif',classic:'-apple-system,BlinkMacSystemFont,"Helvetica Neue",Helvetica,Arial,sans-serif',condensed:'"Arial Narrow","Helvetica Neue Condensed",Arial,sans-serif',serif:'Georgia,"Times New Roman",serif'};const stack=stacks[choice]||stacks.helvetica;try{if(document.fonts?.ready)await Promise.race([document.fonts.ready,new Promise(r=>setTimeout(r,1800))]);layer.style.fontFamily=stack;const test=document.createElement('canvas').getContext('2d');test.font=`800 48px ${stack}`;const width=test.measureText('Music lyrics 123').width;if(!Number.isFinite(width)||width<10)throw new Error('font metrics invalid');status.font=true;return true}catch(e){status.font=false;log('font','Font rendering check failed',`${choice}: ${e.message||e}`);select.value='helvetica';layer.style.fontFamily=stacks.helvetica;if(notify)notifyGuard('Selected font could not render reliably. Switched safely to Helvetica.');status.font=true;return true}}
function installFontGuard(){injectHelvetica();const select=$('#fontStyle');if(!select)return;select.addEventListener('change',()=>{fontSanity({notify:true});checkpoint('font-changed')});fontSanity();const prior=window.exportFontFamily;if(typeof prior==='function'){window.exportFontFamily=function(){if($('#fontStyle')?.value==='helvetica')return '"Helvetica Neue",Helvetica,Arial,sans-serif';const v=prior();return v||'"Helvetica Neue",Helvetica,Arial,sans-serif'}}}
function forceRender(reason){const audio=$('#audio');if(!audio||typeof window.renderAt!=='function'&&typeof renderAt!=='function')return;const fn=typeof renderAt==='function'?renderAt:window.renderAt;try{fn(audio.currentTime*1000);sync.lastRepair=performance.now();status.sync=true;log('sync','Renderer resynchronised',reason)}catch(e){status.sync=false;log('sync','Renderer resync failed',e)}}
function syncIntegrity(){const audio=$('#audio');if(!audio||audio.paused||sync.seeking)return;const perf=performance.now(),audioMs=audio.currentTime*1000,wallDelta=perf-sync.lastPerf,audioDelta=audioMs-sync.lastAudioMs;sync.lastPerf=perf;sync.lastAudioMs=audioMs;if(wallDelta>1200&&audioDelta<150){sync.stallCount++;log('sync','Playback stall detected',`wall=${wallDelta.toFixed(0)} audio=${audioDelta.toFixed(0)}`)}if(Math.abs(audioDelta-wallDelta)>380&&wallDelta<1200){status.sync=false;forceRender(`drift ${Math.round(audioDelta-wallDelta)}ms`)}else status.sync=true}
function installSyncGuard(){const audio=$('#audio');if(!audio)return;audio.addEventListener('play',()=>{sync.lastAudioMs=audio.currentTime*1000;sync.lastPerf=performance.now();forceRender('play')});audio.addEventListener('seeking',()=>{sync.seeking=true;checkpoint('seeking')});audio.addEventListener('seeked',()=>{sync.seeking=false;forceRender('seeked')});audio.addEventListener('ratechange',()=>forceRender('ratechange'));audio.addEventListener('loadedmetadata',()=>forceRender('metadata-ready'));audio.addEventListener('timeupdate',()=>{if(performance.now()-sync.lastRepair>400)forceRender('timeupdate heartbeat')});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(()=>forceRender('foreground-resume'),60)});setInterval(syncIntegrity,250)}
async function exportPreflight(){const problems=[];try{if(typeof doc==='undefined'||!doc.lines?.length)problems.push('Add or generate lyrics first.');else if(!lyricSanity())problems.push('Lyrics or lyric timing failed the integrity check.');const af=window.selectedAudioFile||$('#audioFile')?.files?.[0];if(!af&&!$('#audio')?.src)problems.push('Add audio first.');if(af){const v=validateFile(af,'audio');if(!v.ok)problems.push(v.error)}if(!window.MediaRecorder)problems.push('This browser does not support MediaRecorder.');if(!HTMLCanvasElement.prototype.captureStream)problems.push('This browser cannot capture the export canvas.');if(!canvasSanity())problems.push('Export canvas or text rendering is unavailable.');if(!await fontSanity())problems.push('Font rendering failed its preflight check.');const audio=$('#audio');if(audio?.src&&(!Number.isFinite(audio.duration)||audio.duration<=0))problems.push('Audio metadata is not ready.');const est=await estimateStorage();if(est?.quota&&est?.usage&&est.quota-est.usage<100*1024*1024)problems.push('Less than 100 MB browser storage remains. Free space before exporting.');if(!navigator.onLine)log('export','Offline export requested','Local rendering may work; server MP4 conversion may not.');if(problems.length){log('export','Preflight blocked export',problems.join(' | '));notifyGuard(problems[0]);return false}forceRender('pre-export');checkpoint('pre-export');status.export=true;return true}catch(e){log('export','Preflight failed unexpectedly',e);notifyGuard('Export preflight failed safely. Your project was not changed.');return false}}
function exportWatchStart(){clearInterval(exportWatch.timer);exportWatch.active=true;exportWatch.lastProgress=+$('#exportProgress')?.value||0;exportWatch.lastChange=performance.now();exportWatch.timer=setInterval(()=>{if(!exportWatch.active)return;const p=+$('#exportProgress')?.value||0;if(p>exportWatch.lastProgress+.1){exportWatch.lastProgress=p;exportWatch.lastChange=performance.now()}else if(performance.now()-exportWatch.lastChange>25000){log('export','Export watchdog detected no progress',`stuck at ${p}%`);checkpoint('export-stalled');notifyGuard('Export appears stalled. Your project is safe; cancel and retry in low-memory mode.');exportWatch.lastChange=performance.now()}},3000)}
function exportWatchStop(reason){exportWatch.active=false;clearInterval(exportWatch.timer);exportWatch.timer=0;checkpoint(`export-${reason}`)}
function installExportGate(){const btn=$('#exportBtn');if(btn)btn.addEventListener('click',async e=>{const ok=await exportPreflight();if(!ok){e.preventDefault();e.stopImmediatePropagation()}},true);const begin=$('#beginExport');if(begin)begin.addEventListener('click',async e=>{const ok=await exportPreflight();if(!ok){e.preventDefault();e.stopImmediatePropagation();return}exportWatchStart()},true);$('#cancelExport')?.addEventListener('click',()=>exportWatchStop('cancelled'));const dialog=$('#exportDialog');dialog?.addEventListener('close',()=>exportWatchStop('dialog-closed'))}
function mediaRuntimeGuards(){const audio=$('#audio');if(!audio)return;audio.addEventListener('error',()=>{status.media=false;log('audio','Browser could not decode audio',audio.error?.message||audio.error?.code);checkpoint('audio-error');notifyGuard('Audio could not be decoded. Try MP3, M4A, AAC or WAV.')});audio.addEventListener('loadedmetadata',()=>{if(!Number.isFinite(audio.duration)||audio.duration<=0){status.media=false;log('audio','Invalid duration',audio.duration);notifyGuard('Audio duration could not be read.')}else{status.media=true;if(audio.duration>LIMITS.maxDuration){log('audio','Very long audio loaded',audio.duration);notifyGuard('This audio is unusually long; shorter media is safer for browser export.')}}checkpoint('audio-ready')})}
function networkGuards(){window.addEventListener('online',()=>{status.network=true;notifyGuard('Connection restored. Online lyric sources are available again.')});window.addEventListener('offline',()=>{status.network=false;log('network','Browser went offline');checkpoint('offline');notifyGuard('Offline mode: existing projects and the local LRC maker still work.')})}
function globalErrorGuards(){window.addEventListener('error',e=>{log('runtime',e.message||'Unhandled error',`${e.filename||''}:${e.lineno||''}`);checkpoint('runtime-error')});window.addEventListener('unhandledrejection',e=>{log('promise','Unhandled promise rejection',e.reason?.message||e.reason);checkpoint('promise-error')});window.addEventListener('pagehide',()=>checkpoint('pagehide'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')checkpoint('backgrounded')})}
function protectNavigation(){window.addEventListener('beforeunload',()=>checkpoint('beforeunload'))}
function expose(){window.__LV_GUARD__={status,checkpoint,exportPreflight,lyricSanity,fontSanity,forceRender,validateFile,logs:()=>{try{return JSON.parse(sessionStorage.getItem(LOG_KEY)||'[]')}catch{return[]}},recovery:()=>{try{return JSON.parse(sessionStorage.getItem(CHECKPOINT_KEY)||'null')}catch{return null}}}}
function init(){startupCheck();guardInput('audioFile','audio');guardInput('lyricsFile','lyrics');guardInput('backgroundFile','background');installFontGuard();installSyncGuard();installExportGate();mediaRuntimeGuards();networkGuards();globalErrorGuards();protectNavigation();expose();setInterval(()=>checkpoint('periodic'),30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
