// Lyric Video Visualier — single-shell site identity, section hierarchy, navigation and footer.
(function(){
'use strict';
const q=s=>document.querySelector(s);
function jump(sel){const el=q(sel);if(!el)return;el.scrollIntoView({behavior:'smooth',block:'start'});}
function installScript(src,marker){if(document.querySelector(`script[data-${marker}]`))return;const s=document.createElement('script');s.src=src;s.defer=true;s.setAttribute(`data-${marker}`,'1');s.onerror=()=>console.error(`Lyric Video Visualier: ${src} failed to load`);document.head.appendChild(s)}
function installLocalLyricImporter(){installScript('lrc_import_fix.js','lv-lrc-fix')}
function installControlFixes(){installScript('control_fixes.js','lv-control-fixes')}
function installStyles(){if(document.getElementById('lv-site-chrome-style'))return;const style=document.createElement('style');style.id='lv-site-chrome-style';style.textContent=`
.lv-site-nav,.lv-site-intro,.lv-site-footer,.lv-section-heading{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif}
/* There is only ONE visible top setup. The legacy app header and duplicate progress strip are hidden. */
.app>header,#flowStatus{display:none!important}
.lv-site-nav{display:grid;grid-template-columns:minmax(280px,1.25fr) 2fr auto;gap:24px;align-items:end;padding:18px 22px;border-bottom:1px solid rgba(255,255,255,.28);background:#050505;color:#fff;position:relative;z-index:20}
.lv-nav-wordmark{display:grid;gap:3px;cursor:pointer}.lv-nav-wordmark strong{font-size:clamp(24px,2.5vw,40px);line-height:.92;letter-spacing:-.055em;font-weight:850}.lv-nav-wordmark span{font-size:9px;letter-spacing:.10em;color:#8b8b8b}
.lv-nav-links{display:flex;justify-content:flex-end;align-items:center;gap:18px;flex-wrap:wrap}.lv-nav-links button,.lv-nav-links a{font:700 10px/1 "Helvetica Neue",Helvetica,Arial,sans-serif;letter-spacing:.065em;color:#f7f7f7;background:none;border:0;padding:0;text-decoration:none;cursor:pointer}.lv-nav-links button:hover,.lv-nav-links a:hover{opacity:.55}
.lv-nav-actions{display:flex;gap:8px;align-items:center;justify-content:flex-end}.lv-nav-actions button{border:1px solid rgba(255,255,255,.22);background:#0c0c0c;color:#fff;padding:9px 12px;font:750 10px/1 "Helvetica Neue",Helvetica,Arial,sans-serif;letter-spacing:.06em;cursor:pointer}.lv-nav-actions .lv-export{background:#f4f4f4;color:#050505;border-color:#f4f4f4}
.lv-site-intro{background:#050505;color:#fff;padding:54px 22px 60px;border-bottom:1px solid rgba(255,255,255,.22)}.lv-kicker{margin:0 0 18px;font-size:10px;font-weight:800;letter-spacing:.11em}.lv-site-intro h1{margin:0;font-size:clamp(54px,9vw,142px);line-height:.82;letter-spacing:-.07em;font-weight:850;max-width:1200px}.lv-intro-meta{margin-top:30px;padding-top:15px;border-top:1px solid rgba(255,255,255,.3);display:grid;grid-template-columns:1.5fr 1fr;gap:36px}.lv-intro-meta p{margin:0;max-width:720px;font-size:12px;line-height:1.45;color:#d0d0d0}.lv-intro-meta p:last-child{font-size:10px;color:#858585;letter-spacing:.035em;line-height:1.6}
.lv-section-heading{width:100%;margin:0 0 14px;padding:0 0 10px;border-bottom:1px solid rgba(255,255,255,.25);display:flex;align-items:baseline;justify-content:space-between;gap:16px;color:#fff}.lv-section-heading strong{font-size:clamp(22px,3vw,40px);line-height:.95;letter-spacing:-.045em;font-weight:850}.lv-section-heading span{font-size:9px;line-height:1.3;letter-spacing:.09em;color:#777;text-align:right}
.editor>.lv-section-heading{width:min(100%,430px)}
.controls .panel{position:relative}.controls .panel>h2{font-size:15px!important;line-height:1!important;letter-spacing:-.02em!important;color:#f5f5f5!important;font-weight:800!important;text-transform:none!important;margin:0 0 14px!important;padding:0 0 10px!important;border-bottom:1px solid rgba(255,255,255,.16)!important}
.controls .panel>h2::before{content:"SECTION / ";font-size:8px;letter-spacing:.11em;color:#666;margin-right:5px;vertical-align:2px}
.lv-site-footer{background:#030303;color:#f5f5f5;border-top:1px solid rgba(255,255,255,.28);padding:44px 22px 18px}.lv-footer-title{font-size:clamp(48px,8vw,120px);line-height:.82;letter-spacing:-.07em;font-weight:850;margin-bottom:42px}.lv-footer-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:28px;padding-top:16px;border-top:1px solid rgba(255,255,255,.25)}.lv-footer-grid section{display:flex;flex-direction:column;gap:8px;min-width:0}.lv-footer-label{margin:0 0 8px;font-size:9px;font-weight:800;letter-spacing:.10em;color:#797979}.lv-footer-grid a,.lv-footer-grid span{font-size:11px;line-height:1.35;color:#d6d6d6;text-decoration:none}.lv-footer-grid a:hover{color:#fff}.lv-footer-bottom{margin-top:42px;padding-top:12px;border-top:1px solid rgba(255,255,255,.2);display:grid;grid-template-columns:1fr 1fr auto;align-items:center;gap:18px;font-size:9px;letter-spacing:.055em;color:#7f7f7f}.lv-footer-bottom button{border:0;background:none;color:#f3f3f3;font:700 9px/1 "Helvetica Neue",Helvetica,Arial,sans-serif;letter-spacing:.06em;cursor:pointer;padding:0}
@media(max-width:900px){.lv-site-nav{grid-template-columns:1fr;align-items:start;gap:14px}.lv-nav-links{justify-content:flex-start;gap:14px}.lv-nav-actions{justify-content:flex-start}.lv-site-intro{padding-top:42px}.lv-intro-meta{grid-template-columns:1fr}.lv-footer-grid{grid-template-columns:1fr 1fr}.lv-footer-bottom{grid-template-columns:1fr;align-items:start}.lv-footer-bottom button{text-align:left}}
@media(max-width:520px){.lv-footer-grid{grid-template-columns:1fr}.lv-site-intro h1{font-size:clamp(48px,17vw,78px)}.lv-nav-wordmark strong{font-size:27px}.lv-nav-links{row-gap:11px}.lv-section-heading strong{font-size:24px}.lv-section-heading{align-items:flex-start}.lv-section-heading span{max-width:120px}}
`;document.head.append(style)}
function addSectionHeadings(){
 const editor=q('.editor');
 if(editor&&!editor.querySelector(':scope>.lv-section-heading')){
   const h=document.createElement('div');h.className='lv-section-heading';h.innerHTML='<strong>CREATE / PREVIEW</strong><span>MEDIA · LYRICS · COMPOSITION</span>';editor.insertBefore(h,editor.firstChild);
 }
 const controls=q('#controls');
 if(controls&&!controls.previousElementSibling?.classList?.contains('lv-section-heading')){
   const h=document.createElement('div');h.className='lv-section-heading';h.innerHTML='<strong>EDIT / CONTROL</strong><span>STYLE · TIMING · BACKGROUND · PROJECT</span>';controls.parentNode.insertBefore(h,controls);
 }
}
function build(){
 if(document.querySelector('.lv-site-nav'))return;
 installLocalLyricImporter();installControlFixes();installStyles();
 const app=q('.app');if(!app)return;
 document.documentElement.classList.add('lv-site-shell');
 const nav=document.createElement('nav');nav.className='lv-site-nav';nav.setAttribute('aria-label','Primary navigation');
 nav.innerHTML=`<div class="lv-nav-wordmark" role="link" tabindex="0" data-jump=".editor"><strong>LINA: LYRIC VIDEO VISUALISER</strong><span>HELVETICA / BLACK / WHITE / APPLE MUSIC–READY WORKFLOW</span></div><div class="lv-nav-links"><button type="button" data-jump=".editor">CREATE</button><button type="button" data-open-lrc>LYRICS / LRC</button><button type="button" data-jump="[data-panel-content='style']">STYLE</button><button type="button" data-jump="[data-panel-content='timing']">TIMING</button><button type="button" data-jump="[data-panel-content='background']">BACKGROUND</button><button type="button" data-jump="[data-panel-content='project']">PROJECT</button><a href="https://github.com/Tezzaaaaaa/lyricvideovisualiser" target="_blank" rel="noopener noreferrer">GITHUB ↗</a></div><div class="lv-nav-actions"><button type="button" data-save>SAVE</button><button type="button" class="lv-export" data-export>EXPORT</button></div>`;
 app.insertBefore(nav,app.firstChild);
 const info=document.createElement('section');info.className='lv-site-intro';info.innerHTML=`<p class="lv-kicker">LINA / LYRIC VIDEO VISUALISER</p><h1>BUILD. SYNC.<br>VISUALISE.</h1><div class="lv-intro-meta"><p>One streamlined workspace for loading audio, importing or generating timed lyrics, styling motion and exporting social-ready lyric video.</p><p>LOCAL-FIRST MEDIA PROCESSING<br>APPLE MUSIC LINK + METADATA SUPPORT<br>LRC / ENHANCED LRC / SRT / TXT</p></div>`;nav.insertAdjacentElement('afterend',info);
 addSectionHeadings();
 const footer=document.createElement('footer');footer.className='lv-site-footer';footer.innerHTML=`<div class="lv-footer-title">LINA:<br>LYRIC VIDEO VISUALISER</div><div class="lv-footer-grid"><section><p class="lv-footer-label">NAVIGATION</p><a href="#" data-jump=".editor">Create</a><a href="#" data-open-lrc>Lyrics / LRC Collector</a><a href="#" data-jump="[data-panel-content='style']">Style</a><a href="#" data-jump="[data-panel-content='timing']">Timing</a><a href="#" data-jump="[data-panel-content='background']">Background</a><a href="#" data-jump="[data-panel-content='project']">Projects</a><a href="#" data-export>Export</a></section><section><p class="lv-footer-label">PROJECT / CONTACT</p><a href="https://github.com/Tezzaaaaaa/lyricvideovisualiser" target="_blank" rel="noopener noreferrer">GitHub Repository ↗</a><a href="https://github.com/Tezzaaaaaa" target="_blank" rel="noopener noreferrer">Developer Profile ↗</a><a href="https://github.com/Tezzaaaaaa/lyricvideovisualiser/issues" target="_blank" rel="noopener noreferrer">Contact / Feedback ↗</a></section><section><p class="lv-footer-label">WORKFLOW</p><span>Apple Music track-link identification</span><span>Synced LRC collection + local generator</span><span>Helvetica-first lyric system</span><span>Metadata-heavy export workflow</span><span>Fail-safe project recovery</span></section><section><p class="lv-footer-label">INFORMATION</p><span>Audio and project media are processed locally where supported.</span><span>Apple Music is used for track identification, metadata and sharing links only.</span><span>This project does not bypass DRM or provide protected Apple Music audio.</span></section></div><div class="lv-footer-bottom"><span>© ${new Date().getFullYear()} LINA: LYRIC VIDEO VISUALISER</span><span>HELVETICA / BLACK / WHITE / SYSTEM 01</span><button type="button" data-top>BACK TO TOP ↑</button></div>`;app.insertAdjacentElement('afterend',footer);
 document.addEventListener('click',e=>{const j=e.target.closest('[data-jump]');if(j){e.preventDefault();jump(j.dataset.jump);return}const lrc=e.target.closest('[data-open-lrc]');if(lrc){e.preventDefault();q('#openCollector')?.click();return}const ex=e.target.closest('[data-export]');if(ex){e.preventDefault();q('#exportBtn')?.click();return}const save=e.target.closest('[data-save]');if(save){e.preventDefault();q('#saveProject')?.click();return}if(e.target.closest('[data-top]'))window.scrollTo({top:0,behavior:'smooth'})});
 nav.querySelector('.lv-nav-wordmark')?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();jump('.editor')}});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})();