/* KEFE Visual FX — independent Canvas effects inspired by modern browser effect editors. */
(() => {
    'use strict';
    if (typeof window === 'undefined' || typeof window.render !== 'function' || !window.state || !window.canvas) return;

    const FX_KEY = 'kefe-visual-fx-v1';
    const originalRender = window.render;
    const fxInput = document.createElement('canvas');
    const fxInputCtx = fxInput.getContext('2d', { alpha: false });
    const scratch = document.createElement('canvas');
    const scratchCtx = scratch.getContext('2d', { alpha: true });
    const defaults = { visualFx:'none', fxIntensity:.55, fxSpeed:1, fxGrain:.18, fxScanlines:.24, fxRgbShift:.008, fxBlur:.18, fxShake:.18, fxVignette:.18, fxHalftone:.22 };
    Object.assign(window.state.style, defaults, window.state.style);
    try { const saved=JSON.parse(localStorage.getItem(FX_KEY)||'{}'); if(saved&&typeof saved==='object')Object.assign(window.state.style,saved); } catch(_){}
    const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,Number(v)||0));
    const seeded=(t,s=0)=>{const n=Math.sin(t*12.9898+s*78.233)*43758.5453;return n-Math.floor(n);};
    function resize(w,h){if(fxInput.width!==w||fxInput.height!==h){fxInput.width=w;fxInput.height=h;}if(scratch.width!==w||scratch.height!==h){scratch.width=w;scratch.height=h;}}
    function save(){try{const s=window.state.style;localStorage.setItem(FX_KEY,JSON.stringify({visualFx:s.visualFx,fxIntensity:s.fxIntensity,fxSpeed:s.fxSpeed,fxGrain:s.fxGrain,fxScanlines:s.fxScanlines,fxRgbShift:s.fxRgbShift,fxBlur:s.fxBlur,fxShake:s.fxShake,fxVignette:s.fxVignette,fxHalftone:s.fxHalftone}));}catch(_){}
    }
    function base(c,s,w,h){c.drawImage(s,0,0,w,h);}
    function vignette(c,w,h,a){if(a<=0)return;const g=c.createRadialGradient(w/2,h/2,Math.min(w,h)*.18,w/2,h/2,Math.max(w,h)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.62,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${clamp(a,0,.78)})`);c.fillStyle=g;c.fillRect(0,0,w,h);}
    function scan(c,w,h,a,step=4){if(a<=0)return;c.save();c.globalAlpha=clamp(a,0,.65);c.fillStyle='#000';for(let y=0;y<h;y+=Math.max(2,step))c.fillRect(0,y,w,1);c.restore();}
    function grain(c,w,h,a,t){if(a<=0)return;const size=Math.max(1,Math.round(Math.min(w,h)*.004)),count=Math.round(w*h*clamp(a,0,.4)*.000012);c.save();c.globalAlpha=clamp(a*.55,0,.24);for(let i=0;i<count;i++){const x=Math.floor(seeded(t*97+i,1)*w),y=Math.floor(seeded(t*89+i,2)*h),v=seeded(t*71+i,3)>.5?255:0;c.fillStyle=`rgb(${v},${v},${v})`;c.fillRect(x,y,size,size);}c.restore();}
    function rgb(c,s,w,h,a){const px=Math.max(1,Math.round(Math.min(w,h)*a));c.save();c.globalCompositeOperation='screen';c.globalAlpha=.42;c.drawImage(s,px,0,w,h,0,0,w,h);c.restore();scratchCtx.clearRect(0,0,w,h);scratchCtx.globalAlpha=.42;scratchCtx.drawImage(s,-px,0,w,h,0,0,w,h);scratchCtx.globalAlpha=1;c.save();c.globalCompositeOperation='screen';c.drawImage(scratch,0,0);c.restore();}
    function bloom(c,s,w,h,a){if(a<=0)return;scratchCtx.clearRect(0,0,w,h);scratchCtx.filter=`blur(${Math.max(1,Math.min(28,Math.min(w,h)*a*.018))}px)`;scratchCtx.globalAlpha=clamp(a*.5,0,.5);scratchCtx.drawImage(s,0,0,w,h);scratchCtx.filter='none';scratchCtx.globalAlpha=1;c.save();c.globalCompositeOperation='screen';c.globalAlpha=clamp(a*.85,0,.7);c.drawImage(scratch,0,0);c.restore();}
    function shake(c,s,w,h,a,t,speed){const e=a*(.45+.55*Math.sin(t*speed*9.3)**2),x=(seeded(t*speed*7.1,4)-.5)*w*.018*e,y=(seeded(t*speed*8.7,5)-.5)*h*.018*e,r=(seeded(t*speed*6.2,6)-.5)*.012*e;c.save();c.translate(w/2+x,h/2+y);c.rotate(r);c.scale(1+e*.008,1+e*.008);c.drawImage(s,-w/2,-h/2,w,h);c.restore();}
    function motion(c,s,w,h,a,t){if(a<=0)return;c.save();c.globalCompositeOperation='screen';c.globalAlpha=a*.12;const dx=Math.sin(t*3.2)*Math.min(w,h)*.006*a,dy=Math.cos(t*2.4)*Math.min(w,h)*.004*a;for(let i=1;i<=4;i++)c.drawImage(s,dx*i,dy*i,w,h);c.restore();}
    function glitch(c,s,w,h,a,t){if(seeded(Math.floor(t*8),19)>.72){const n=2+Math.floor(seeded(t*10,20)*6);for(let i=0;i<n;i++){const y=Math.floor(seeded(t*11+i,21)*h),sh=Math.max(2,Math.floor(h*(.002+seeded(i,22)*.012)*a)),shift=(seeded(t*13+i,23)-.5)*w*.06*a;c.drawImage(s,0,y,w,sh,shift,y,w,sh);}}c.save();c.globalAlpha=a*.18;c.fillStyle='#fff';c.fillRect(0,Math.floor(seeded(t*31,24)*h),w,Math.max(1,Math.floor(h*.0015)));c.restore();}
    function halftone(c,s,w,h,a){if(a<=0)return;const sample=Math.min(128,Math.max(32,Math.round(w/Math.max(5,Math.min(w,h)*.012))));scratch.width=sample;scratch.height=Math.max(1,Math.round(h/w*sample));scratchCtx.filter='grayscale(1) contrast(1.2)';scratchCtx.drawImage(s,0,0,scratch.width,scratch.height);scratchCtx.filter='none';const d=scratchCtx.getImageData(0,0,scratch.width,scratch.height).data,sx=w/scratch.width,sy=h/scratch.height;c.save();c.globalAlpha=clamp(a*.75,0,.7);c.fillStyle='#000';for(let y=0;y<scratch.height;y++)for(let x=0;x<scratch.width;x++){const i=(y*scratch.width+x)*4,lum=(d[i]+d[i+1]+d[i+2])/765,r=(1-lum)*Math.min(sx,sy)*.48;if(r<.5)continue;c.beginPath();c.arc(x*sx+sx/2,y*sy+sy/2,r,0,Math.PI*2);c.fill();}c.restore();scratch.width=w;scratch.height=h;}
    function apply(c,w,h,s,t,src){const fx=s.visualFx||'none',a=clamp(s.fxIntensity),speed=Math.max(.1,Number(s.fxSpeed)||1);if(fx==='none')return;c.clearRect(0,0,w,h);switch(fx){case'vhs':shake(c,src,w,h,a*.45,t,speed*.8);rgb(c,src,w,h,.004*a);motion(c,src,w,h,a*.65,t);scan(c,w,h,clamp(s.fxScanlines*.75+a*.12),5);grain(c,w,h,s.fxGrain+a*.28,t);glitch(c,src,w,h,a*.7,t);break;case'crt':base(c,src,w,h);rgb(c,src,w,h,.0025*a);bloom(c,src,w,h,a*.55);scan(c,w,h,s.fxScanlines+a*.22,4);vignette(c,w,h,s.fxVignette+a*.18);break;case'rgb':base(c,src,w,h);rgb(c,src,w,h,s.fxRgbShift*a);break;case'bloom':base(c,src,w,h);bloom(c,src,w,h,a);break;case'motion':base(c,src,w,h);motion(c,src,w,h,s.fxBlur*a+a*.35,t);break;case'shake':shake(c,src,w,h,s.fxShake*a+a*.35,t,speed);motion(c,src,w,h,a*.35,t);break;case'glitch':base(c,src,w,h);glitch(c,src,w,h,a,t);rgb(c,src,w,h,.004*a);break;case'halftone':base(c,src,w,h);halftone(c,src,w,h,s.fxHalftone*a);break;case'vignette':base(c,src,w,h);vignette(c,w,h,s.fxVignette*a+.12*a);break;default:base(c,src,w,h);}}
    window.render=function(ctx,w,h,appState,mediaCache){const fx=appState?.style?.visualFx||'none';if(!fx||fx==='none')return originalRender(ctx,w,h,appState,mediaCache);resize(w,h);originalRender(fxInputCtx,w,h,appState,mediaCache);ctx.save();apply(ctx,w,h,appState.style,Number(appState.playback?.currentTime)||0,fxInput);ctx.restore();};
    const labels={none:'Off — clean KEFE rendering',vhs:'VHS — tape wobble, chroma bleed, scanlines and grain',crt:'CRT — scanlines, glow, RGB separation and vignette',rgb:'RGB Shift — chromatic lens separation',bloom:'Bloom — soft highlight diffusion and light bleed',motion:'Motion Blur — directional trails',shake:'Camera Shake — subtle handheld movement',glitch:'Glitch — controlled signal breaks and chromatic distortion',halftone:'Halftone — graphic print-screen texture',vignette:'Vignette — restrained cinematic edge falloff'};
    function setFx(name){if(!labels[name]||window.isExporting)return;window.state.style.visualFx=name;qsa('.kefe-fx-button').forEach(b=>b.classList.toggle('active-effect',b.dataset.fx===name));const l=document.getElementById('visualFxLabel');if(l)l.textContent=labels[name];save();window.redrawCurrentPreviewFrame?.();}
    function range(parent,key,text,min,max,step,suffix=''){const row=document.createElement('div');row.className='control-row';const label=document.createElement('label'),value=document.createElement('span'),input=document.createElement('input');value.style.marginLeft='6px';label.textContent=text;input.type='range';input.min=min;input.max=max;input.step=step;input.value=window.state.style[key];const show=()=>value.textContent=`${Number(input.value).toFixed(step<.1?2:1)}${suffix}`;label.appendChild(value);show();input.addEventListener('input',()=>{window.state.style[key]=Number(input.value);show();save();window.redrawCurrentPreviewFrame?.();});row.append(label,input);parent.appendChild(row);}
    function ui(){const anchor=document.querySelector('.sidebar .section:has(#effectControls)');if(!anchor||document.getElementById('visualFxSection'))return;const sec=document.createElement('div');sec.className='section';sec.id='visualFxSection';const h=document.createElement('h3');h.textContent='Visual FX';sec.appendChild(h);const buttons=document.createElement('div');buttons.className='effect-buttons';['none','vhs','crt','rgb','bloom','motion','shake','glitch','halftone','vignette'].forEach(n=>{const b=document.createElement('button');b.type='button';b.dataset.fx=n;b.className='kefe-fx-button';b.textContent=n==='none'?'Off':n==='rgb'?'RGB':n[0].toUpperCase()+n.slice(1);b.addEventListener('click',()=>setFx(n));buttons.appendChild(b);});sec.appendChild(buttons);const d=document.createElement('div');d.className='effect-label';d.id='visualFxLabel';d.textContent=labels[window.state.style.visualFx]||labels.none;sec.appendChild(d);const controls=document.createElement('div');range(controls,'fxIntensity','Intensity',0,1,.05);range(controls,'fxSpeed','Animation speed',.25,2.5,.05,'×');sec.appendChild(controls);anchor.insertAdjacentElement('afterend',sec);qsa('.kefe-fx-button').forEach(b=>b.classList.toggle('active-effect',b.dataset.fx===window.state.style.visualFx));}
    ui();
})();
